{{-- Auto-generated Tailwind safe classes for backdrop filters --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}
<div style="display: none;">

    <!-- Backdrop Blur Classes --}}
    <div class="backdrop-blur-none backdrop-blur-sm backdrop-blur backdrop-blur-md backdrop-blur-lg backdrop-blur-xl backdrop-blur-2xl backdrop-blur-3xl"></div>

</div>