{{-- Auto-generated Tailwind safe classes for visibility --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Visibility classes --}}
<div class="block hidden inline-block"></div>

{{-- @sm responsive visibility classes --}}
<div class="@sm:block @sm:hidden @sm:inline-block"></div>

{{-- sm responsive visibility classes --}}
<div class="sm:block sm:hidden sm:inline-block"></div>

{{-- @md responsive visibility classes --}}
<div class="@md:block @md:hidden @md:inline-block"></div>

{{-- md responsive visibility classes --}}
<div class="md:block md:hidden md:inline-block"></div>

{{-- @lg responsive visibility classes --}}
<div class="@lg:block @lg:hidden @lg:inline-block"></div>

{{-- lg responsive visibility classes --}}
<div class="lg:block lg:hidden lg:inline-block"></div>

{{-- @xl responsive visibility classes --}}
<div class="@xl:block @xl:hidden @xl:inline-block"></div>

{{-- xl responsive visibility classes --}}
<div class="xl:block xl:hidden xl:inline-block"></div>

{{-- @2xl responsive visibility classes --}}
<div class="@2xl:block @2xl:hidden @2xl:inline-block"></div>

{{-- 2xl responsive visibility classes --}}
<div class="2xl:block 2xl:hidden 2xl:inline-block"></div>

{{-- @3xl responsive visibility classes --}}
<div class="@3xl:block @3xl:hidden @3xl:inline-block"></div>

{{-- 3xl responsive visibility classes --}}
<div class="3xl:block 3xl:hidden 3xl:inline-block"></div>

{{-- @7xl responsive visibility classes --}}
<div class="@7xl:block @7xl:hidden @7xl:inline-block"></div>

{{-- 7xl responsive visibility classes --}}
<div class="7xl:block 7xl:hidden 7xl:inline-block"></div>
