{{-- Auto-generated Tailwind safe classes for flex --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Flex classes --}}
<div class="flex flex-row flex-col"></div>

{{-- @3xl responsive flex classes --}}
<div class="@3xl:flex @3xl:flex-row @3xl:flex-col"></div>

{{-- @7xl responsive flex classes --}}
<div class="@7xl:flex @7xl:flex-row @7xl:flex-col"></div>
