{{-- Auto-generated Tailwind safe classes for overflow --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Overflow classes --}}
<div class="overflow-auto overflow-scroll overflow-visible overflow-hidden"></div>

{{-- Overflow-x classes --}}
<div class="overflow-x-auto overflow-x-scroll overflow-x-visible overflow-x-hidden"></div>

{{-- Overflow-y classes --}}
<div class="overflow-y-auto overflow-y-scroll overflow-y-visible overflow-y-hidden"></div>
