{{-- Auto-generated Tailwind safe classes for margin --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Margin all classes --}}
<div class="m-0 m-px m-0.5 m-1 m-1.5 m-2 m-2.5 m-3 m-3.5 m-4 m-5 m-6 m-7 m-8 m-9 m-10 m-11 m-12 m-14 m-16 m-20 m-24 m-28 m-32 m-36 m-40 m-44 m-48 m-52 m-56 m-60 m-64 m-72 m-80 m-96"></div>

{{-- Negative margin all classes --}}
<div class="-m-px -m-0.5 -m-1 -m-1.5 -m-2 -m-2.5 -m-3 -m-3.5 -m-4 -m-5 -m-6 -m-7 -m-8 -m-9 -m-10 -m-11 -m-12 -m-14 -m-16 -m-20 -m-24 -m-28 -m-32 -m-36 -m-40 -m-44 -m-48 -m-52 -m-56 -m-60 -m-64 -m-72 -m-80 -m-96"></div>

{{-- @3xl responsive margin all classes --}}
<div class="@3xl:m-0 @3xl:m-px @3xl:m-0.5 @3xl:m-1 @3xl:m-1.5 @3xl:m-2 @3xl:m-2.5 @3xl:m-3 @3xl:m-3.5 @3xl:m-4 @3xl:m-5 @3xl:m-6 @3xl:m-7 @3xl:m-8 @3xl:m-9 @3xl:m-10 @3xl:m-11 @3xl:m-12 @3xl:m-14 @3xl:m-16 @3xl:m-20 @3xl:m-24 @3xl:m-28 @3xl:m-32 @3xl:m-36 @3xl:m-40 @3xl:m-44 @3xl:m-48 @3xl:m-52 @3xl:m-56 @3xl:m-60 @3xl:m-64 @3xl:m-72 @3xl:m-80 @3xl:m-96"></div>

{{-- @3xl responsive negative margin all classes --}}
<div class="@3xl:-m-px @3xl:-m-0.5 @3xl:-m-1 @3xl:-m-1.5 @3xl:-m-2 @3xl:-m-2.5 @3xl:-m-3 @3xl:-m-3.5 @3xl:-m-4 @3xl:-m-5 @3xl:-m-6 @3xl:-m-7 @3xl:-m-8 @3xl:-m-9 @3xl:-m-10 @3xl:-m-11 @3xl:-m-12 @3xl:-m-14 @3xl:-m-16 @3xl:-m-20 @3xl:-m-24 @3xl:-m-28 @3xl:-m-32 @3xl:-m-36 @3xl:-m-40 @3xl:-m-44 @3xl:-m-48 @3xl:-m-52 @3xl:-m-56 @3xl:-m-60 @3xl:-m-64 @3xl:-m-72 @3xl:-m-80 @3xl:-m-96"></div>

{{-- @5xl responsive margin all classes --}}
<div class="@5xl:m-0 @5xl:m-px @5xl:m-0.5 @5xl:m-1 @5xl:m-1.5 @5xl:m-2 @5xl:m-2.5 @5xl:m-3 @5xl:m-3.5 @5xl:m-4 @5xl:m-5 @5xl:m-6 @5xl:m-7 @5xl:m-8 @5xl:m-9 @5xl:m-10 @5xl:m-11 @5xl:m-12 @5xl:m-14 @5xl:m-16 @5xl:m-20 @5xl:m-24 @5xl:m-28 @5xl:m-32 @5xl:m-36 @5xl:m-40 @5xl:m-44 @5xl:m-48 @5xl:m-52 @5xl:m-56 @5xl:m-60 @5xl:m-64 @5xl:m-72 @5xl:m-80 @5xl:m-96"></div>

{{-- @5xl responsive negative margin all classes --}}
<div class="@5xl:-m-px @5xl:-m-0.5 @5xl:-m-1 @5xl:-m-1.5 @5xl:-m-2 @5xl:-m-2.5 @5xl:-m-3 @5xl:-m-3.5 @5xl:-m-4 @5xl:-m-5 @5xl:-m-6 @5xl:-m-7 @5xl:-m-8 @5xl:-m-9 @5xl:-m-10 @5xl:-m-11 @5xl:-m-12 @5xl:-m-14 @5xl:-m-16 @5xl:-m-20 @5xl:-m-24 @5xl:-m-28 @5xl:-m-32 @5xl:-m-36 @5xl:-m-40 @5xl:-m-44 @5xl:-m-48 @5xl:-m-52 @5xl:-m-56 @5xl:-m-60 @5xl:-m-64 @5xl:-m-72 @5xl:-m-80 @5xl:-m-96"></div>

{{-- Margin top classes --}}
<div class="mt-0 mt-px mt-0.5 mt-1 mt-1.5 mt-2 mt-2.5 mt-3 mt-3.5 mt-4 mt-5 mt-6 mt-7 mt-8 mt-9 mt-10 mt-11 mt-12 mt-14 mt-16 mt-20 mt-24 mt-28 mt-32 mt-36 mt-40 mt-44 mt-48 mt-52 mt-56 mt-60 mt-64 mt-72 mt-80 mt-96"></div>

{{-- Negative margin top classes --}}
<div class="-mt-px -mt-0.5 -mt-1 -mt-1.5 -mt-2 -mt-2.5 -mt-3 -mt-3.5 -mt-4 -mt-5 -mt-6 -mt-7 -mt-8 -mt-9 -mt-10 -mt-11 -mt-12 -mt-14 -mt-16 -mt-20 -mt-24 -mt-28 -mt-32 -mt-36 -mt-40 -mt-44 -mt-48 -mt-52 -mt-56 -mt-60 -mt-64 -mt-72 -mt-80 -mt-96"></div>

{{-- @3xl responsive margin top classes --}}
<div class="@3xl:mt-0 @3xl:mt-px @3xl:mt-0.5 @3xl:mt-1 @3xl:mt-1.5 @3xl:mt-2 @3xl:mt-2.5 @3xl:mt-3 @3xl:mt-3.5 @3xl:mt-4 @3xl:mt-5 @3xl:mt-6 @3xl:mt-7 @3xl:mt-8 @3xl:mt-9 @3xl:mt-10 @3xl:mt-11 @3xl:mt-12 @3xl:mt-14 @3xl:mt-16 @3xl:mt-20 @3xl:mt-24 @3xl:mt-28 @3xl:mt-32 @3xl:mt-36 @3xl:mt-40 @3xl:mt-44 @3xl:mt-48 @3xl:mt-52 @3xl:mt-56 @3xl:mt-60 @3xl:mt-64 @3xl:mt-72 @3xl:mt-80 @3xl:mt-96"></div>

{{-- @3xl responsive negative margin top classes --}}
<div class="@3xl:-mt-px @3xl:-mt-0.5 @3xl:-mt-1 @3xl:-mt-1.5 @3xl:-mt-2 @3xl:-mt-2.5 @3xl:-mt-3 @3xl:-mt-3.5 @3xl:-mt-4 @3xl:-mt-5 @3xl:-mt-6 @3xl:-mt-7 @3xl:-mt-8 @3xl:-mt-9 @3xl:-mt-10 @3xl:-mt-11 @3xl:-mt-12 @3xl:-mt-14 @3xl:-mt-16 @3xl:-mt-20 @3xl:-mt-24 @3xl:-mt-28 @3xl:-mt-32 @3xl:-mt-36 @3xl:-mt-40 @3xl:-mt-44 @3xl:-mt-48 @3xl:-mt-52 @3xl:-mt-56 @3xl:-mt-60 @3xl:-mt-64 @3xl:-mt-72 @3xl:-mt-80 @3xl:-mt-96"></div>

{{-- @5xl responsive margin top classes --}}
<div class="@5xl:mt-0 @5xl:mt-px @5xl:mt-0.5 @5xl:mt-1 @5xl:mt-1.5 @5xl:mt-2 @5xl:mt-2.5 @5xl:mt-3 @5xl:mt-3.5 @5xl:mt-4 @5xl:mt-5 @5xl:mt-6 @5xl:mt-7 @5xl:mt-8 @5xl:mt-9 @5xl:mt-10 @5xl:mt-11 @5xl:mt-12 @5xl:mt-14 @5xl:mt-16 @5xl:mt-20 @5xl:mt-24 @5xl:mt-28 @5xl:mt-32 @5xl:mt-36 @5xl:mt-40 @5xl:mt-44 @5xl:mt-48 @5xl:mt-52 @5xl:mt-56 @5xl:mt-60 @5xl:mt-64 @5xl:mt-72 @5xl:mt-80 @5xl:mt-96"></div>

{{-- @5xl responsive negative margin top classes --}}
<div class="@5xl:-mt-px @5xl:-mt-0.5 @5xl:-mt-1 @5xl:-mt-1.5 @5xl:-mt-2 @5xl:-mt-2.5 @5xl:-mt-3 @5xl:-mt-3.5 @5xl:-mt-4 @5xl:-mt-5 @5xl:-mt-6 @5xl:-mt-7 @5xl:-mt-8 @5xl:-mt-9 @5xl:-mt-10 @5xl:-mt-11 @5xl:-mt-12 @5xl:-mt-14 @5xl:-mt-16 @5xl:-mt-20 @5xl:-mt-24 @5xl:-mt-28 @5xl:-mt-32 @5xl:-mt-36 @5xl:-mt-40 @5xl:-mt-44 @5xl:-mt-48 @5xl:-mt-52 @5xl:-mt-56 @5xl:-mt-60 @5xl:-mt-64 @5xl:-mt-72 @5xl:-mt-80 @5xl:-mt-96"></div>

{{-- Margin right classes --}}
<div class="mr-0 mr-px mr-0.5 mr-1 mr-1.5 mr-2 mr-2.5 mr-3 mr-3.5 mr-4 mr-5 mr-6 mr-7 mr-8 mr-9 mr-10 mr-11 mr-12 mr-14 mr-16 mr-20 mr-24 mr-28 mr-32 mr-36 mr-40 mr-44 mr-48 mr-52 mr-56 mr-60 mr-64 mr-72 mr-80 mr-96"></div>

{{-- Negative margin right classes --}}
<div class="-mr-px -mr-0.5 -mr-1 -mr-1.5 -mr-2 -mr-2.5 -mr-3 -mr-3.5 -mr-4 -mr-5 -mr-6 -mr-7 -mr-8 -mr-9 -mr-10 -mr-11 -mr-12 -mr-14 -mr-16 -mr-20 -mr-24 -mr-28 -mr-32 -mr-36 -mr-40 -mr-44 -mr-48 -mr-52 -mr-56 -mr-60 -mr-64 -mr-72 -mr-80 -mr-96"></div>

{{-- @3xl responsive margin right classes --}}
<div class="@3xl:mr-0 @3xl:mr-px @3xl:mr-0.5 @3xl:mr-1 @3xl:mr-1.5 @3xl:mr-2 @3xl:mr-2.5 @3xl:mr-3 @3xl:mr-3.5 @3xl:mr-4 @3xl:mr-5 @3xl:mr-6 @3xl:mr-7 @3xl:mr-8 @3xl:mr-9 @3xl:mr-10 @3xl:mr-11 @3xl:mr-12 @3xl:mr-14 @3xl:mr-16 @3xl:mr-20 @3xl:mr-24 @3xl:mr-28 @3xl:mr-32 @3xl:mr-36 @3xl:mr-40 @3xl:mr-44 @3xl:mr-48 @3xl:mr-52 @3xl:mr-56 @3xl:mr-60 @3xl:mr-64 @3xl:mr-72 @3xl:mr-80 @3xl:mr-96"></div>

{{-- @3xl responsive negative margin right classes --}}
<div class="@3xl:-mr-px @3xl:-mr-0.5 @3xl:-mr-1 @3xl:-mr-1.5 @3xl:-mr-2 @3xl:-mr-2.5 @3xl:-mr-3 @3xl:-mr-3.5 @3xl:-mr-4 @3xl:-mr-5 @3xl:-mr-6 @3xl:-mr-7 @3xl:-mr-8 @3xl:-mr-9 @3xl:-mr-10 @3xl:-mr-11 @3xl:-mr-12 @3xl:-mr-14 @3xl:-mr-16 @3xl:-mr-20 @3xl:-mr-24 @3xl:-mr-28 @3xl:-mr-32 @3xl:-mr-36 @3xl:-mr-40 @3xl:-mr-44 @3xl:-mr-48 @3xl:-mr-52 @3xl:-mr-56 @3xl:-mr-60 @3xl:-mr-64 @3xl:-mr-72 @3xl:-mr-80 @3xl:-mr-96"></div>

{{-- @5xl responsive margin right classes --}}
<div class="@5xl:mr-0 @5xl:mr-px @5xl:mr-0.5 @5xl:mr-1 @5xl:mr-1.5 @5xl:mr-2 @5xl:mr-2.5 @5xl:mr-3 @5xl:mr-3.5 @5xl:mr-4 @5xl:mr-5 @5xl:mr-6 @5xl:mr-7 @5xl:mr-8 @5xl:mr-9 @5xl:mr-10 @5xl:mr-11 @5xl:mr-12 @5xl:mr-14 @5xl:mr-16 @5xl:mr-20 @5xl:mr-24 @5xl:mr-28 @5xl:mr-32 @5xl:mr-36 @5xl:mr-40 @5xl:mr-44 @5xl:mr-48 @5xl:mr-52 @5xl:mr-56 @5xl:mr-60 @5xl:mr-64 @5xl:mr-72 @5xl:mr-80 @5xl:mr-96"></div>

{{-- @5xl responsive negative margin right classes --}}
<div class="@5xl:-mr-px @5xl:-mr-0.5 @5xl:-mr-1 @5xl:-mr-1.5 @5xl:-mr-2 @5xl:-mr-2.5 @5xl:-mr-3 @5xl:-mr-3.5 @5xl:-mr-4 @5xl:-mr-5 @5xl:-mr-6 @5xl:-mr-7 @5xl:-mr-8 @5xl:-mr-9 @5xl:-mr-10 @5xl:-mr-11 @5xl:-mr-12 @5xl:-mr-14 @5xl:-mr-16 @5xl:-mr-20 @5xl:-mr-24 @5xl:-mr-28 @5xl:-mr-32 @5xl:-mr-36 @5xl:-mr-40 @5xl:-mr-44 @5xl:-mr-48 @5xl:-mr-52 @5xl:-mr-56 @5xl:-mr-60 @5xl:-mr-64 @5xl:-mr-72 @5xl:-mr-80 @5xl:-mr-96"></div>

{{-- Margin bottom classes --}}
<div class="mb-0 mb-px mb-0.5 mb-1 mb-1.5 mb-2 mb-2.5 mb-3 mb-3.5 mb-4 mb-5 mb-6 mb-7 mb-8 mb-9 mb-10 mb-11 mb-12 mb-14 mb-16 mb-20 mb-24 mb-28 mb-32 mb-36 mb-40 mb-44 mb-48 mb-52 mb-56 mb-60 mb-64 mb-72 mb-80 mb-96"></div>

{{-- Negative margin bottom classes --}}
<div class="-mb-px -mb-0.5 -mb-1 -mb-1.5 -mb-2 -mb-2.5 -mb-3 -mb-3.5 -mb-4 -mb-5 -mb-6 -mb-7 -mb-8 -mb-9 -mb-10 -mb-11 -mb-12 -mb-14 -mb-16 -mb-20 -mb-24 -mb-28 -mb-32 -mb-36 -mb-40 -mb-44 -mb-48 -mb-52 -mb-56 -mb-60 -mb-64 -mb-72 -mb-80 -mb-96"></div>

{{-- @3xl responsive margin bottom classes --}}
<div class="@3xl:mb-0 @3xl:mb-px @3xl:mb-0.5 @3xl:mb-1 @3xl:mb-1.5 @3xl:mb-2 @3xl:mb-2.5 @3xl:mb-3 @3xl:mb-3.5 @3xl:mb-4 @3xl:mb-5 @3xl:mb-6 @3xl:mb-7 @3xl:mb-8 @3xl:mb-9 @3xl:mb-10 @3xl:mb-11 @3xl:mb-12 @3xl:mb-14 @3xl:mb-16 @3xl:mb-20 @3xl:mb-24 @3xl:mb-28 @3xl:mb-32 @3xl:mb-36 @3xl:mb-40 @3xl:mb-44 @3xl:mb-48 @3xl:mb-52 @3xl:mb-56 @3xl:mb-60 @3xl:mb-64 @3xl:mb-72 @3xl:mb-80 @3xl:mb-96"></div>

{{-- @3xl responsive negative margin bottom classes --}}
<div class="@3xl:-mb-px @3xl:-mb-0.5 @3xl:-mb-1 @3xl:-mb-1.5 @3xl:-mb-2 @3xl:-mb-2.5 @3xl:-mb-3 @3xl:-mb-3.5 @3xl:-mb-4 @3xl:-mb-5 @3xl:-mb-6 @3xl:-mb-7 @3xl:-mb-8 @3xl:-mb-9 @3xl:-mb-10 @3xl:-mb-11 @3xl:-mb-12 @3xl:-mb-14 @3xl:-mb-16 @3xl:-mb-20 @3xl:-mb-24 @3xl:-mb-28 @3xl:-mb-32 @3xl:-mb-36 @3xl:-mb-40 @3xl:-mb-44 @3xl:-mb-48 @3xl:-mb-52 @3xl:-mb-56 @3xl:-mb-60 @3xl:-mb-64 @3xl:-mb-72 @3xl:-mb-80 @3xl:-mb-96"></div>

{{-- @5xl responsive margin bottom classes --}}
<div class="@5xl:mb-0 @5xl:mb-px @5xl:mb-0.5 @5xl:mb-1 @5xl:mb-1.5 @5xl:mb-2 @5xl:mb-2.5 @5xl:mb-3 @5xl:mb-3.5 @5xl:mb-4 @5xl:mb-5 @5xl:mb-6 @5xl:mb-7 @5xl:mb-8 @5xl:mb-9 @5xl:mb-10 @5xl:mb-11 @5xl:mb-12 @5xl:mb-14 @5xl:mb-16 @5xl:mb-20 @5xl:mb-24 @5xl:mb-28 @5xl:mb-32 @5xl:mb-36 @5xl:mb-40 @5xl:mb-44 @5xl:mb-48 @5xl:mb-52 @5xl:mb-56 @5xl:mb-60 @5xl:mb-64 @5xl:mb-72 @5xl:mb-80 @5xl:mb-96"></div>

{{-- @5xl responsive negative margin bottom classes --}}
<div class="@5xl:-mb-px @5xl:-mb-0.5 @5xl:-mb-1 @5xl:-mb-1.5 @5xl:-mb-2 @5xl:-mb-2.5 @5xl:-mb-3 @5xl:-mb-3.5 @5xl:-mb-4 @5xl:-mb-5 @5xl:-mb-6 @5xl:-mb-7 @5xl:-mb-8 @5xl:-mb-9 @5xl:-mb-10 @5xl:-mb-11 @5xl:-mb-12 @5xl:-mb-14 @5xl:-mb-16 @5xl:-mb-20 @5xl:-mb-24 @5xl:-mb-28 @5xl:-mb-32 @5xl:-mb-36 @5xl:-mb-40 @5xl:-mb-44 @5xl:-mb-48 @5xl:-mb-52 @5xl:-mb-56 @5xl:-mb-60 @5xl:-mb-64 @5xl:-mb-72 @5xl:-mb-80 @5xl:-mb-96"></div>

{{-- Margin left classes --}}
<div class="ml-0 ml-px ml-0.5 ml-1 ml-1.5 ml-2 ml-2.5 ml-3 ml-3.5 ml-4 ml-5 ml-6 ml-7 ml-8 ml-9 ml-10 ml-11 ml-12 ml-14 ml-16 ml-20 ml-24 ml-28 ml-32 ml-36 ml-40 ml-44 ml-48 ml-52 ml-56 ml-60 ml-64 ml-72 ml-80 ml-96"></div>

{{-- Negative margin left classes --}}
<div class="-ml-px -ml-0.5 -ml-1 -ml-1.5 -ml-2 -ml-2.5 -ml-3 -ml-3.5 -ml-4 -ml-5 -ml-6 -ml-7 -ml-8 -ml-9 -ml-10 -ml-11 -ml-12 -ml-14 -ml-16 -ml-20 -ml-24 -ml-28 -ml-32 -ml-36 -ml-40 -ml-44 -ml-48 -ml-52 -ml-56 -ml-60 -ml-64 -ml-72 -ml-80 -ml-96"></div>

{{-- @3xl responsive margin left classes --}}
<div class="@3xl:ml-0 @3xl:ml-px @3xl:ml-0.5 @3xl:ml-1 @3xl:ml-1.5 @3xl:ml-2 @3xl:ml-2.5 @3xl:ml-3 @3xl:ml-3.5 @3xl:ml-4 @3xl:ml-5 @3xl:ml-6 @3xl:ml-7 @3xl:ml-8 @3xl:ml-9 @3xl:ml-10 @3xl:ml-11 @3xl:ml-12 @3xl:ml-14 @3xl:ml-16 @3xl:ml-20 @3xl:ml-24 @3xl:ml-28 @3xl:ml-32 @3xl:ml-36 @3xl:ml-40 @3xl:ml-44 @3xl:ml-48 @3xl:ml-52 @3xl:ml-56 @3xl:ml-60 @3xl:ml-64 @3xl:ml-72 @3xl:ml-80 @3xl:ml-96"></div>

{{-- @3xl responsive negative margin left classes --}}
<div class="@3xl:-ml-px @3xl:-ml-0.5 @3xl:-ml-1 @3xl:-ml-1.5 @3xl:-ml-2 @3xl:-ml-2.5 @3xl:-ml-3 @3xl:-ml-3.5 @3xl:-ml-4 @3xl:-ml-5 @3xl:-ml-6 @3xl:-ml-7 @3xl:-ml-8 @3xl:-ml-9 @3xl:-ml-10 @3xl:-ml-11 @3xl:-ml-12 @3xl:-ml-14 @3xl:-ml-16 @3xl:-ml-20 @3xl:-ml-24 @3xl:-ml-28 @3xl:-ml-32 @3xl:-ml-36 @3xl:-ml-40 @3xl:-ml-44 @3xl:-ml-48 @3xl:-ml-52 @3xl:-ml-56 @3xl:-ml-60 @3xl:-ml-64 @3xl:-ml-72 @3xl:-ml-80 @3xl:-ml-96"></div>

{{-- @5xl responsive margin left classes --}}
<div class="@5xl:ml-0 @5xl:ml-px @5xl:ml-0.5 @5xl:ml-1 @5xl:ml-1.5 @5xl:ml-2 @5xl:ml-2.5 @5xl:ml-3 @5xl:ml-3.5 @5xl:ml-4 @5xl:ml-5 @5xl:ml-6 @5xl:ml-7 @5xl:ml-8 @5xl:ml-9 @5xl:ml-10 @5xl:ml-11 @5xl:ml-12 @5xl:ml-14 @5xl:ml-16 @5xl:ml-20 @5xl:ml-24 @5xl:ml-28 @5xl:ml-32 @5xl:ml-36 @5xl:ml-40 @5xl:ml-44 @5xl:ml-48 @5xl:ml-52 @5xl:ml-56 @5xl:ml-60 @5xl:ml-64 @5xl:ml-72 @5xl:ml-80 @5xl:ml-96"></div>

{{-- @5xl responsive negative margin left classes --}}
<div class="@5xl:-ml-px @5xl:-ml-0.5 @5xl:-ml-1 @5xl:-ml-1.5 @5xl:-ml-2 @5xl:-ml-2.5 @5xl:-ml-3 @5xl:-ml-3.5 @5xl:-ml-4 @5xl:-ml-5 @5xl:-ml-6 @5xl:-ml-7 @5xl:-ml-8 @5xl:-ml-9 @5xl:-ml-10 @5xl:-ml-11 @5xl:-ml-12 @5xl:-ml-14 @5xl:-ml-16 @5xl:-ml-20 @5xl:-ml-24 @5xl:-ml-28 @5xl:-ml-32 @5xl:-ml-36 @5xl:-ml-40 @5xl:-ml-44 @5xl:-ml-48 @5xl:-ml-52 @5xl:-ml-56 @5xl:-ml-60 @5xl:-ml-64 @5xl:-ml-72 @5xl:-ml-80 @5xl:-ml-96"></div>

{{-- Margin horizontal classes --}}
<div class="mx-0 mx-px mx-0.5 mx-1 mx-1.5 mx-2 mx-2.5 mx-3 mx-3.5 mx-4 mx-5 mx-6 mx-7 mx-8 mx-9 mx-10 mx-11 mx-12 mx-14 mx-16 mx-20 mx-24 mx-28 mx-32 mx-36 mx-40 mx-44 mx-48 mx-52 mx-56 mx-60 mx-64 mx-72 mx-80 mx-96"></div>

{{-- Negative margin horizontal classes --}}
<div class="-mx-px -mx-0.5 -mx-1 -mx-1.5 -mx-2 -mx-2.5 -mx-3 -mx-3.5 -mx-4 -mx-5 -mx-6 -mx-7 -mx-8 -mx-9 -mx-10 -mx-11 -mx-12 -mx-14 -mx-16 -mx-20 -mx-24 -mx-28 -mx-32 -mx-36 -mx-40 -mx-44 -mx-48 -mx-52 -mx-56 -mx-60 -mx-64 -mx-72 -mx-80 -mx-96"></div>

{{-- @3xl responsive margin horizontal classes --}}
<div class="@3xl:mx-0 @3xl:mx-px @3xl:mx-0.5 @3xl:mx-1 @3xl:mx-1.5 @3xl:mx-2 @3xl:mx-2.5 @3xl:mx-3 @3xl:mx-3.5 @3xl:mx-4 @3xl:mx-5 @3xl:mx-6 @3xl:mx-7 @3xl:mx-8 @3xl:mx-9 @3xl:mx-10 @3xl:mx-11 @3xl:mx-12 @3xl:mx-14 @3xl:mx-16 @3xl:mx-20 @3xl:mx-24 @3xl:mx-28 @3xl:mx-32 @3xl:mx-36 @3xl:mx-40 @3xl:mx-44 @3xl:mx-48 @3xl:mx-52 @3xl:mx-56 @3xl:mx-60 @3xl:mx-64 @3xl:mx-72 @3xl:mx-80 @3xl:mx-96"></div>

{{-- @3xl responsive negative margin horizontal classes --}}
<div class="@3xl:-mx-px @3xl:-mx-0.5 @3xl:-mx-1 @3xl:-mx-1.5 @3xl:-mx-2 @3xl:-mx-2.5 @3xl:-mx-3 @3xl:-mx-3.5 @3xl:-mx-4 @3xl:-mx-5 @3xl:-mx-6 @3xl:-mx-7 @3xl:-mx-8 @3xl:-mx-9 @3xl:-mx-10 @3xl:-mx-11 @3xl:-mx-12 @3xl:-mx-14 @3xl:-mx-16 @3xl:-mx-20 @3xl:-mx-24 @3xl:-mx-28 @3xl:-mx-32 @3xl:-mx-36 @3xl:-mx-40 @3xl:-mx-44 @3xl:-mx-48 @3xl:-mx-52 @3xl:-mx-56 @3xl:-mx-60 @3xl:-mx-64 @3xl:-mx-72 @3xl:-mx-80 @3xl:-mx-96"></div>

{{-- @5xl responsive margin horizontal classes --}}
<div class="@5xl:mx-0 @5xl:mx-px @5xl:mx-0.5 @5xl:mx-1 @5xl:mx-1.5 @5xl:mx-2 @5xl:mx-2.5 @5xl:mx-3 @5xl:mx-3.5 @5xl:mx-4 @5xl:mx-5 @5xl:mx-6 @5xl:mx-7 @5xl:mx-8 @5xl:mx-9 @5xl:mx-10 @5xl:mx-11 @5xl:mx-12 @5xl:mx-14 @5xl:mx-16 @5xl:mx-20 @5xl:mx-24 @5xl:mx-28 @5xl:mx-32 @5xl:mx-36 @5xl:mx-40 @5xl:mx-44 @5xl:mx-48 @5xl:mx-52 @5xl:mx-56 @5xl:mx-60 @5xl:mx-64 @5xl:mx-72 @5xl:mx-80 @5xl:mx-96"></div>

{{-- @5xl responsive negative margin horizontal classes --}}
<div class="@5xl:-mx-px @5xl:-mx-0.5 @5xl:-mx-1 @5xl:-mx-1.5 @5xl:-mx-2 @5xl:-mx-2.5 @5xl:-mx-3 @5xl:-mx-3.5 @5xl:-mx-4 @5xl:-mx-5 @5xl:-mx-6 @5xl:-mx-7 @5xl:-mx-8 @5xl:-mx-9 @5xl:-mx-10 @5xl:-mx-11 @5xl:-mx-12 @5xl:-mx-14 @5xl:-mx-16 @5xl:-mx-20 @5xl:-mx-24 @5xl:-mx-28 @5xl:-mx-32 @5xl:-mx-36 @5xl:-mx-40 @5xl:-mx-44 @5xl:-mx-48 @5xl:-mx-52 @5xl:-mx-56 @5xl:-mx-60 @5xl:-mx-64 @5xl:-mx-72 @5xl:-mx-80 @5xl:-mx-96"></div>

{{-- Margin vertical classes --}}
<div class="my-0 my-px my-0.5 my-1 my-1.5 my-2 my-2.5 my-3 my-3.5 my-4 my-5 my-6 my-7 my-8 my-9 my-10 my-11 my-12 my-14 my-16 my-20 my-24 my-28 my-32 my-36 my-40 my-44 my-48 my-52 my-56 my-60 my-64 my-72 my-80 my-96"></div>

{{-- Negative margin vertical classes --}}
<div class="-my-px -my-0.5 -my-1 -my-1.5 -my-2 -my-2.5 -my-3 -my-3.5 -my-4 -my-5 -my-6 -my-7 -my-8 -my-9 -my-10 -my-11 -my-12 -my-14 -my-16 -my-20 -my-24 -my-28 -my-32 -my-36 -my-40 -my-44 -my-48 -my-52 -my-56 -my-60 -my-64 -my-72 -my-80 -my-96"></div>

{{-- @3xl responsive margin vertical classes --}}
<div class="@3xl:my-0 @3xl:my-px @3xl:my-0.5 @3xl:my-1 @3xl:my-1.5 @3xl:my-2 @3xl:my-2.5 @3xl:my-3 @3xl:my-3.5 @3xl:my-4 @3xl:my-5 @3xl:my-6 @3xl:my-7 @3xl:my-8 @3xl:my-9 @3xl:my-10 @3xl:my-11 @3xl:my-12 @3xl:my-14 @3xl:my-16 @3xl:my-20 @3xl:my-24 @3xl:my-28 @3xl:my-32 @3xl:my-36 @3xl:my-40 @3xl:my-44 @3xl:my-48 @3xl:my-52 @3xl:my-56 @3xl:my-60 @3xl:my-64 @3xl:my-72 @3xl:my-80 @3xl:my-96"></div>

{{-- @3xl responsive negative margin vertical classes --}}
<div class="@3xl:-my-px @3xl:-my-0.5 @3xl:-my-1 @3xl:-my-1.5 @3xl:-my-2 @3xl:-my-2.5 @3xl:-my-3 @3xl:-my-3.5 @3xl:-my-4 @3xl:-my-5 @3xl:-my-6 @3xl:-my-7 @3xl:-my-8 @3xl:-my-9 @3xl:-my-10 @3xl:-my-11 @3xl:-my-12 @3xl:-my-14 @3xl:-my-16 @3xl:-my-20 @3xl:-my-24 @3xl:-my-28 @3xl:-my-32 @3xl:-my-36 @3xl:-my-40 @3xl:-my-44 @3xl:-my-48 @3xl:-my-52 @3xl:-my-56 @3xl:-my-60 @3xl:-my-64 @3xl:-my-72 @3xl:-my-80 @3xl:-my-96"></div>

{{-- @5xl responsive margin vertical classes --}}
<div class="@5xl:my-0 @5xl:my-px @5xl:my-0.5 @5xl:my-1 @5xl:my-1.5 @5xl:my-2 @5xl:my-2.5 @5xl:my-3 @5xl:my-3.5 @5xl:my-4 @5xl:my-5 @5xl:my-6 @5xl:my-7 @5xl:my-8 @5xl:my-9 @5xl:my-10 @5xl:my-11 @5xl:my-12 @5xl:my-14 @5xl:my-16 @5xl:my-20 @5xl:my-24 @5xl:my-28 @5xl:my-32 @5xl:my-36 @5xl:my-40 @5xl:my-44 @5xl:my-48 @5xl:my-52 @5xl:my-56 @5xl:my-60 @5xl:my-64 @5xl:my-72 @5xl:my-80 @5xl:my-96"></div>

{{-- @5xl responsive negative margin vertical classes --}}
<div class="@5xl:-my-px @5xl:-my-0.5 @5xl:-my-1 @5xl:-my-1.5 @5xl:-my-2 @5xl:-my-2.5 @5xl:-my-3 @5xl:-my-3.5 @5xl:-my-4 @5xl:-my-5 @5xl:-my-6 @5xl:-my-7 @5xl:-my-8 @5xl:-my-9 @5xl:-my-10 @5xl:-my-11 @5xl:-my-12 @5xl:-my-14 @5xl:-my-16 @5xl:-my-20 @5xl:-my-24 @5xl:-my-28 @5xl:-my-32 @5xl:-my-36 @5xl:-my-40 @5xl:-my-44 @5xl:-my-48 @5xl:-my-52 @5xl:-my-56 @5xl:-my-60 @5xl:-my-64 @5xl:-my-72 @5xl:-my-80 @5xl:-my-96"></div>
