{{-- Auto-generated complete Tailwind safe classes --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}
<div style="display: none;">

    {{-- Grid classes --}}
    <div class="grid grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-5 grid-cols-6 grid-cols-7 grid-cols-8 grid-cols-9 grid-cols-10 grid-cols-11 grid-cols-12 grid-cols-13 grid-cols-14 grid-cols-15 grid-cols-16 grid-cols-17 grid-cols-18 grid-cols-19 grid-cols-20"></div>

    <div class="col-span-1 col-span-2 col-span-3 col-span-4 col-span-5 col-span-6 col-span-7 col-span-8 col-span-9 col-span-10 col-span-11 col-span-12 col-span-13 col-span-14 col-span-15 col-span-16 col-span-17 col-span-18 col-span-19 col-span-20"></div>

    <div class="@md:col-span-1 @md:col-span-2 @md:col-span-3 @md:col-span-4 @md:col-span-5 @md:col-span-6 @md:col-span-7 @md:col-span-8 @md:col-span-9 @md:col-span-10 @md:col-span-11 @md:col-span-12 @md:col-span-13 @md:col-span-14 @md:col-span-15 @md:col-span-16 @md:col-span-17 @md:col-span-18 @md:col-span-19 @md:col-span-20"></div>
    <div class="@lg:col-span-1 @lg:col-span-2 @lg:col-span-3 @lg:col-span-4 @lg:col-span-5 @lg:col-span-6 @lg:col-span-7 @lg:col-span-8 @lg:col-span-9 @lg:col-span-10 @lg:col-span-11 @lg:col-span-12 @lg:col-span-13 @lg:col-span-14 @lg:col-span-15 @lg:col-span-16 @lg:col-span-17 @lg:col-span-18 @lg:col-span-19 @lg:col-span-20"></div>
    <div class="@xl:col-span-1 @xl:col-span-2 @xl:col-span-3 @xl:col-span-4 @xl:col-span-5 @xl:col-span-6 @xl:col-span-7 @xl:col-span-8 @xl:col-span-9 @xl:col-span-10 @xl:col-span-11 @xl:col-span-12 @xl:col-span-13 @xl:col-span-14 @xl:col-span-15 @xl:col-span-16 @xl:col-span-17 @xl:col-span-18 @xl:col-span-19 @xl:col-span-20"></div>
    <div class="@2xl:col-span-1 @2xl:col-span-2 @2xl:col-span-3 @2xl:col-span-4 @2xl:col-span-5 @2xl:col-span-6 @2xl:col-span-7 @2xl:col-span-8 @2xl:col-span-9 @2xl:col-span-10 @2xl:col-span-11 @2xl:col-span-12 @2xl:col-span-13 @2xl:col-span-14 @2xl:col-span-15 @2xl:col-span-16 @2xl:col-span-17 @2xl:col-span-18 @2xl:col-span-19 @2xl:col-span-20"></div>
    <div class="@3xl:col-span-1 @3xl:col-span-2 @3xl:col-span-3 @3xl:col-span-4 @3xl:col-span-5 @3xl:col-span-6 @3xl:col-span-7 @3xl:col-span-8 @3xl:col-span-9 @3xl:col-span-10 @3xl:col-span-11 @3xl:col-span-12 @3xl:col-span-13 @3xl:col-span-14 @3xl:col-span-15 @3xl:col-span-16 @3xl:col-span-17 @3xl:col-span-18 @3xl:col-span-19 @3xl:col-span-20"></div>
    <div class="@4xl:col-span-1 @4xl:col-span-2 @4xl:col-span-3 @4xl:col-span-4 @4xl:col-span-5 @4xl:col-span-6 @4xl:col-span-7 @4xl:col-span-8 @4xl:col-span-9 @4xl:col-span-10 @4xl:col-span-11 @4xl:col-span-12 @4xl:col-span-13 @4xl:col-span-14 @4xl:col-span-15 @4xl:col-span-16 @4xl:col-span-17 @4xl:col-span-18 @4xl:col-span-19 @4xl:col-span-20"></div>
    <div class="@7xl:col-span-1 @7xl:col-span-2 @7xl:col-span-3 @7xl:col-span-4 @7xl:col-span-5 @7xl:col-span-6 @7xl:col-span-7 @7xl:col-span-8 @7xl:col-span-9 @7xl:col-span-10 @7xl:col-span-11 @7xl:col-span-12 @7xl:col-span-13 @7xl:col-span-14 @7xl:col-span-15 @7xl:col-span-16 @7xl:col-span-17 @7xl:col-span-18 @7xl:col-span-19 @7xl:col-span-20"></div>
    <div class="@3xl:col-span-1 @3xl:col-span-2 @3xl:col-span-3 @3xl:col-span-4 @3xl:col-span-5 @3xl:col-span-6 @3xl:col-span-7 @3xl:col-span-8 @3xl:col-span-9 @3xl:col-span-10 @3xl:col-span-11 @3xl:col-span-12 @3xl:col-span-13 @3xl:col-span-14 @3xl:col-span-15 @3xl:col-span-16 @3xl:col-span-17 @3xl:col-span-18 @3xl:col-span-19 @3xl:col-span-20"></div>
    <div class="@7xl:col-span-1 @7xl:col-span-2 @7xl:col-span-3 @7xl:col-span-4 @7xl:col-span-5 @7xl:col-span-6 @7xl:col-span-7 @7xl:col-span-8 @7xl:col-span-9 @7xl:col-span-10 @7xl:col-span-11 @7xl:col-span-12 @7xl:col-span-13 @7xl:col-span-14 @7xl:col-span-15 @7xl:col-span-16 @7xl:col-span-17 @7xl:col-span-18 @7xl:col-span-19 @7xl:col-span-20"></div>

    {{-- Width utilities --}}
    <div class="w-1/10 w-1/5 w-3/10 w-2/5 w-1/2 w-3/5 w-7/10 w-4/5 w-9/10 w-1/3 w-1/4 w-2/3 w-3/4 w-full w-auto w-screen w-fit w-3xs w-2xs w-xs w-sm w-md w-lg w-xl w-2xl w-3xl w-4xl w-5xl w-6xl w-7xl"></div>
    <div class="@3xl:w-1/10 @3xl:w-1/5 @3xl:w-3/10 @3xl:w-2/5 @3xl:w-1/2 @3xl:w-3/5 @3xl:w-7/10 @3xl:w-4/5 @3xl:w-9/10 @3xl:w-1/3 @3xl:w-1/4 @3xl:w-2/3 @3xl:w-3/4 @3xl:w-full @3xl:w-auto @3xl:w-screen @3xl:w-fit @3xl:w-3xs @3xl:w-2xs @3xl:w-xs @3xl:w-sm @3xl:w-md @3xl:w-lg @3xl:w-xl @3xl:w-2xl @3xl:w-3xl @3xl:w-4xl @3xl:w-5xl @3xl:w-6xl @3xl:w-7xl"></div>
    <div class="@7xl:w-1/10 @7xl:w-1/5 @7xl:w-3/10 @7xl:w-2/5 @7xl:w-1/2 @7xl:w-3/5 @7xl:w-7/10 @7xl:w-4/5 @7xl:w-9/10 @7xl:w-1/3 @7xl:w-1/4 @7xl:w-2/3 @7xl:w-3/4 @7xl:w-full @7xl:w-auto @7xl:w-screen @7xl:w-fit @7xl:w-3xs @7xl:w-2xs @7xl:w-xs @7xl:w-sm @7xl:w-md @7xl:w-lg @7xl:w-xl @7xl:w-2xl @7xl:w-3xl @7xl:w-4xl @7xl:w-5xl @7xl:w-6xl @7xl:w-7xl"></div>

    {{-- Height utilities --}}
    <div class="h-0 h-px h-1 h-2 h-4 h-8 h-12 h-16 h-24 h-32 h-48 h-64 h-80 h-96 h-1/2 h-1/3 h-2/3 h-1/4 h-3/4 h-1/5 h-2/5 h-3/5 h-4/5 h-full h-screen h-auto"></div>
    <div class="@3xl:h-0 @3xl:h-px @3xl:h-1 @3xl:h-2 @3xl:h-4 @3xl:h-8 @3xl:h-12 @3xl:h-16 @3xl:h-24 @3xl:h-32 @3xl:h-48 @3xl:h-64 @3xl:h-80 @3xl:h-96 @3xl:h-1/2 @3xl:h-1/3 @3xl:h-2/3 @3xl:h-1/4 @3xl:h-3/4 @3xl:h-1/5 @3xl:h-2/5 @3xl:h-3/5 @3xl:h-4/5 @3xl:h-full @3xl:h-screen @3xl:h-auto"></div>
    <div class="@7xl:h-0 @7xl:h-px @7xl:h-1 @7xl:h-2 @7xl:h-4 @7xl:h-8 @7xl:h-12 @7xl:h-16 @7xl:h-24 @7xl:h-32 @7xl:h-48 @7xl:h-64 @7xl:h-80 @7xl:h-96 @7xl:h-1/2 @7xl:h-1/3 @7xl:h-2/3 @7xl:h-1/4 @7xl:h-3/4 @7xl:h-1/5 @7xl:h-2/5 @7xl:h-3/5 @7xl:h-4/5 @7xl:h-full @7xl:h-screen @7xl:h-auto"></div>

    {{-- Min Height utilities --}}
    <div class="min-h-0 min-h-px min-h-1 min-h-2 min-h-4 min-h-8 min-h-12 min-h-16 min-h-24 min-h-32 min-h-48 min-h-64 min-h-80 min-h-96 min-h-1/2 min-h-1/3 min-h-2/3 min-h-1/4 min-h-3/4 min-h-1/5 min-h-2/5 min-h-3/5 min-h-4/5 min-h-full min-h-screen"></div>
    <div class="@3xl:min-h-0 @3xl:min-h-px @3xl:min-h-1 @3xl:min-h-2 @3xl:min-h-4 @3xl:min-h-8 @3xl:min-h-12 @3xl:min-h-16 @3xl:min-h-24 @3xl:min-h-32 @3xl:min-h-48 @3xl:min-h-64 @3xl:min-h-80 @3xl:min-h-96 @3xl:min-h-1/2 @3xl:min-h-1/3 @3xl:min-h-2/3 @3xl:min-h-1/4 @3xl:min-h-3/4 @3xl:min-h-1/5 @3xl:min-h-2/5 @3xl:min-h-3/5 @3xl:min-h-4/5 @3xl:min-h-full @3xl:min-h-screen"></div>
    <div class="@7xl:min-h-0 @7xl:min-h-px @7xl:min-h-1 @7xl:min-h-2 @7xl:min-h-4 @7xl:min-h-8 @7xl:min-h-12 @7xl:min-h-16 @7xl:min-h-24 @7xl:min-h-32 @7xl:min-h-48 @7xl:min-h-64 @7xl:min-h-80 @7xl:min-h-96 @7xl:min-h-1/2 @7xl:min-h-1/3 @7xl:min-h-2/3 @7xl:min-h-1/4 @7xl:min-h-3/4 @7xl:min-h-1/5 @7xl:min-h-2/5 @7xl:min-h-3/5 @7xl:min-h-4/5 @7xl:min-h-full @7xl:min-h-screen"></div>

    <div class="flex flex-row flex-col"></div>
    <div class="@md:flex @md:flex-row @md:flex-col"></div>
    <div class="@lg:flex @lg:flex-row @lg:flex-col"></div>

    <div class="gap-0 gap-1 gap-2 gap-3 gap-4 gap-5 gap-6 gap-7 gap-8 gap-9 gap-10 gap-11 gap-12 gap-13 gap-14 gap-15 gap-16 gap-17 gap-18 gap-19 gap-20 gap-21 gap-22 gap-23 gap-24 gap-25 gap-26 gap-27 gap-28 gap-29 gap-30 gap-31 gap-32 gap-33 gap-34 gap-35 gap-36 gap-37 gap-38 gap-39 gap-40"></div>
    <div class="@3xl:gap-0 @3xl:gap-1 @3xl:gap-2 @3xl:gap-3 @3xl:gap-4 @3xl:gap-5 @3xl:gap-6 @3xl:gap-7 @3xl:gap-8 @3xl:gap-9 @3xl:gap-10 @3xl:gap-11 @3xl:gap-12 @3xl:gap-13 @3xl:gap-14 @3xl:gap-15 @3xl:gap-16 @3xl:gap-17 @3xl:gap-18 @3xl:gap-19 @3xl:gap-20 @3xl:gap-21 @3xl:gap-22 @3xl:gap-23 @3xl:gap-24 @3xl:gap-25 @3xl:gap-26 @3xl:gap-27 @3xl:gap-28 @3xl:gap-29 @3xl:gap-30 @3xl:gap-31 @3xl:gap-32 @3xl:gap-33 @3xl:gap-34 @3xl:gap-35 @3xl:gap-36 @3xl:gap-37 @3xl:gap-38 @3xl:gap-39 @3xl:gap-40"></div>
    <div class="@7xl:gap-0 @7xl:gap-1 @7xl:gap-2 @7xl:gap-3 @7xl:gap-4 @7xl:gap-5 @7xl:gap-6 @7xl:gap-7 @7xl:gap-8 @7xl:gap-9 @7xl:gap-10 @7xl:gap-11 @7xl:gap-12 @7xl:gap-13 @7xl:gap-14 @7xl:gap-15 @7xl:gap-16 @7xl:gap-17 @7xl:gap-18 @7xl:gap-19 @7xl:gap-20 @7xl:gap-21 @7xl:gap-22 @7xl:gap-23 @7xl:gap-24 @7xl:gap-25 @7xl:gap-26 @7xl:gap-27 @7xl:gap-28 @7xl:gap-29 @7xl:gap-30 @7xl:gap-31 @7xl:gap-32 @7xl:gap-33 @7xl:gap-34 @7xl:gap-35 @7xl:gap-36 @7xl:gap-37 @7xl:gap-38 @7xl:gap-39 @7xl:gap-40"></div>


    {{-- Responsive visibility --}}
    <div class="@sm:block @sm:hidden @md:block @md:hidden @lg:block @lg:hidden @xl:block @xl:hidden @2xl:block @2xl:hidden @3xl:block @3xl:hidden @4xl:block @4xl:hidden @7xl:block @7xl:hidden"></div>
    <div class="sm:block sm:hidden md:block md:hidden lg:block lg:hidden xl:block xl:hidden 2xl:block 2xl:hidden 3xl:block 3xl:hidden 4xl:block 4xl:hidden 7xl:block 7xl:hidden"></div>
    <div class="inline-block block hidden"></div>

    {{-- Position utilities --}}
    <div class="static relative absolute fixed sticky"></div>
    <div class="@md:static @md:relative @md:absolute @md:fixed @md:sticky"></div>
    <div class="md:static md:relative md:absolute md:fixed md:sticky"></div>
    <div class="@lg:static @lg:relative @lg:absolute @lg:fixed @lg:sticky"></div>
    <div class="lg:static lg:relative lg:absolute lg:fixed lg:sticky"></div>
    <div class="@xl:static @xl:relative @xl:absolute @xl:fixed @xl:sticky"></div>
    <div class="xl:static xl:relative xl:absolute xl:fixed xl:sticky"></div>
    <div class="@2xl:static @2xl:relative @2xl:absolute @2xl:fixed @2xl:sticky"></div>
    <div class="2xl:static 2xl:relative 2xl:absolute 2xl:fixed 2xl:sticky"></div>
    <div class="@3xl:static @3xl:relative @3xl:absolute @3xl:fixed @3xl:sticky"></div>
    <div class="3xl:static 3xl:relative 3xl:absolute 3xl:fixed 3xl:sticky"></div>
    <div class="@4xl:static @4xl:relative @4xl:absolute @4xl:fixed @4xl:sticky"></div>
    <div class="4xl:static 4xl:relative 4xl:absolute 4xl:fixed 4xl:sticky"></div>
    <div class="@7xl:static @7xl:relative @7xl:absolute @7xl:fixed @7xl:sticky"></div>
    <div class="7xl:static 7xl:relative 7xl:absolute 7xl:fixed 7xl:sticky"></div>


    {{-- Text color utilities --}}
    <div class="text-gray-50 text-gray-100 text-gray-200 text-gray-300 text-gray-400 text-gray-500 text-gray-600 text-gray-700 text-gray-800 text-gray-900 text-red-300 text-red-400 text-red-500 text-red-600 text-red-700 text-blue-300 text-blue-400 text-blue-500 text-blue-600 text-blue-700 text-green-300 text-green-400 text-green-500 text-green-600 text-green-700 text-yellow-300 text-yellow-400 text-yellow-500 text-yellow-600 text-yellow-700 text-pink-300 text-pink-400 text-pink-500 text-pink-600 text-pink-700 text-purple-300 text-purple-400 text-purple-500 text-purple-600 text-purple-700 text-indigo-300 text-indigo-400 text-indigo-500 text-indigo-600 text-indigo-700"></div>

    {{-- DaisyUI Theme Text Color Utilities --}}
    <div class="text-base-100 text-base-200 text-base-300 text-base-content text-primary text-primary-content text-secondary text-secondary-content text-accent text-accent-content text-neutral text-neutral-content text-info text-info-content text-success text-success-content text-warning text-warning-content text-error text-error-content"></div>

    {{-- Hover text color utilities --}}
    <div class="hover:text-gray-50 hover:text-gray-100 hover:text-gray-200 hover:text-gray-300 hover:text-gray-400 hover:text-gray-500 hover:text-gray-600 hover:text-gray-700 hover:text-gray-800 hover:text-gray-900 hover:text-red-300 hover:text-red-400 hover:text-red-500 hover:text-red-600 hover:text-red-700 hover:text-blue-300 hover:text-blue-400 hover:text-blue-500 hover:text-blue-600 hover:text-blue-700 hover:text-green-300 hover:text-green-400 hover:text-green-500 hover:text-green-600 hover:text-green-700 hover:text-yellow-300 hover:text-yellow-400 hover:text-yellow-500 hover:text-yellow-600 hover:text-yellow-700 hover:text-pink-300 hover:text-pink-400 hover:text-pink-500 hover:text-pink-600 hover:text-pink-700 hover:text-purple-300 hover:text-purple-400 hover:text-purple-500 hover:text-purple-600 hover:text-purple-700 hover:text-indigo-300 hover:text-indigo-400 hover:text-indigo-500 hover:text-indigo-600 hover:text-indigo-700"></div>

    {{-- DaisyUI Theme Hover Text Color Utilities --}}
    <div class="hover:text-base-100 hover:text-base-200 hover:text-base-300 hover:text-base-content hover:text-primary hover:text-primary-content hover:text-secondary hover:text-secondary-content hover:text-accent hover:text-accent-content hover:text-neutral hover:text-neutral-content hover:text-info hover:text-info-content hover:text-success hover:text-success-content hover:text-warning hover:text-warning-content hover:text-error hover:text-error-content"></div>

    {{-- Background color utilities --}}
    <div class="bg-gray-50 bg-gray-100 bg-gray-200 bg-gray-300 bg-gray-400 bg-gray-500 bg-gray-600 bg-gray-700 bg-gray-800 bg-gray-900 bg-red-300 bg-red-400 bg-red-500 bg-red-600 bg-red-700 bg-blue-300 bg-blue-400 bg-blue-500 bg-blue-600 bg-blue-700 bg-green-300 bg-green-400 bg-green-500 bg-green-600 bg-green-700 bg-yellow-300 bg-yellow-400 bg-yellow-500 bg-yellow-600 bg-yellow-700 bg-pink-300 bg-pink-400 bg-pink-500 bg-pink-600 bg-pink-700 bg-purple-300 bg-purple-400 bg-purple-500 bg-purple-600 bg-purple-700 bg-indigo-300 bg-indigo-400 bg-indigo-500 bg-indigo-600 bg-indigo-700"></div>

    {{-- DaisyUI Theme Background Color Utilities --}}
    <div class="bg-base-100 bg-base-200 bg-base-300 bg-base-content bg-primary bg-primary-content bg-secondary bg-secondary-content bg-accent bg-accent-content bg-neutral bg-neutral-content bg-info bg-info-content bg-success bg-success-content bg-warning bg-warning-content bg-error bg-error-content"></div>

    {{-- Hover background color utilities --}}
    <div class="hover:bg-gray-50 hover:bg-gray-100 hover:bg-gray-200 hover:bg-gray-300 hover:bg-gray-400 hover:bg-gray-500 hover:bg-gray-600 hover:bg-gray-700 hover:bg-gray-800 hover:bg-gray-900 hover:bg-red-300 hover:bg-red-400 hover:bg-red-500 hover:bg-red-600 hover:bg-red-700 hover:bg-blue-300 hover:bg-blue-400 hover:bg-blue-500 hover:bg-blue-600 hover:bg-blue-700 hover:bg-green-300 hover:bg-green-400 hover:bg-green-500 hover:bg-green-600 hover:bg-green-700 hover:bg-yellow-300 hover:bg-yellow-400 hover:bg-yellow-500 hover:bg-yellow-600 hover:bg-yellow-700 hover:bg-pink-300 hover:bg-pink-400 hover:bg-pink-500 hover:bg-pink-600 hover:bg-pink-700 hover:bg-purple-300 hover:bg-purple-400 hover:bg-purple-500 hover:bg-purple-600 hover:bg-purple-700 hover:bg-indigo-300 hover:bg-indigo-400 hover:bg-indigo-500 hover:bg-indigo-600 hover:bg-indigo-700"></div>

    {{-- DaisyUI Theme Hover Background Color Utilities --}}
    <div class="hover:bg-base-100 hover:bg-base-200 hover:bg-base-300 hover:bg-base-content hover:bg-primary hover:bg-primary-content hover:bg-secondary hover:bg-secondary-content hover:bg-accent hover:bg-accent-content hover:bg-neutral hover:bg-neutral-content hover:bg-info hover:bg-info-content hover:bg-success hover:bg-success-content hover:bg-warning hover:bg-warning-content hover:bg-error hover:bg-error-content"></div>

    <div class="items-start items-center items-end items-baseline items-stretch"></div>
    <div class="justify-start justify-center justify-end justify-between justify-around justify-evenly justify-stretch"></div>
    <div class="content-start content-center content-end content-baseline content-stretch"></div>
    <div class="overflow-auto overflow-scroll overflow-visible overflow-hidden"></div>
    <div class="overflow-x-auto overflow-x-scroll overflow-x-visible overflow-x-hidden"></div>
    <div class="overflow-y-auto overflow-y-scroll overflow-y-visible overflow-y-hidden"></div>
    {{-- Layout classes --}}
    <div class="container mx-auto md:container lg:container"></div>

    {{-- Padding classes generated separately --}}

    {{-- Margin classes generated separately --}}

    {{-- Font size utilities --}}
    <div class="text-xs text-sm text-base text-lg text-xl text-2xl text-3xl text-4xl text-5xl text-6xl text-7xl text-8xl text-9xl"></div>
    <div class="@3xl:text-xs @3xl:text-sm @3xl:text-base @3xl:text-lg @3xl:text-xl @3xl:text-2xl @3xl:text-3xl @3xl:text-4xl @3xl:text-5xl @3xl:text-6xl @3xl:text-7xl @3xl:text-8xl @3xl:text-9xl"></div>
    <div class="@7xl:text-xs @7xl:text-sm @7xl:text-base @7xl:text-lg @7xl:text-xl @7xl:text-2xl @7xl:text-3xl @7xl:text-4xl @7xl:text-5xl @7xl:text-6xl @7xl:text-7xl @7xl:text-8xl @7xl:text-9xl"></div>

</div>