{{-- Auto-generated Tailwind safe classes for filters --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}
<div style="display: none;">

    <!-- Blur Classes --}}
    <div class="blur-none blur-sm blur blur-md blur-lg blur-xl blur-2xl blur-3xl"></div>

    <!-- Drop Shadow Classes --}}
    <div class="drop-shadow-none drop-shadow-sm drop-shadow drop-shadow-md drop-shadow-lg drop-shadow-xl drop-shadow-2xl"></div>

</div>