{{-- Auto-generated Tailwind safe classes for position --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Position classes --}}
<div class="static relative absolute fixed sticky"></div>

{{-- @md responsive position classes --}}
<div class="@md:static @md:relative @md:absolute @md:fixed @md:sticky"></div>

{{-- md responsive position classes --}}
<div class="md:static md:relative md:absolute md:fixed md:sticky"></div>

{{-- @lg responsive position classes --}}
<div class="@lg:static @lg:relative @lg:absolute @lg:fixed @lg:sticky"></div>

{{-- lg responsive position classes --}}
<div class="lg:static lg:relative lg:absolute lg:fixed lg:sticky"></div>

{{-- @xl responsive position classes --}}
<div class="@xl:static @xl:relative @xl:absolute @xl:fixed @xl:sticky"></div>

{{-- xl responsive position classes --}}
<div class="xl:static xl:relative xl:absolute xl:fixed xl:sticky"></div>

{{-- @2xl responsive position classes --}}
<div class="@2xl:static @2xl:relative @2xl:absolute @2xl:fixed @2xl:sticky"></div>

{{-- 2xl responsive position classes --}}
<div class="2xl:static 2xl:relative 2xl:absolute 2xl:fixed 2xl:sticky"></div>

{{-- @3xl responsive position classes --}}
<div class="@3xl:static @3xl:relative @3xl:absolute @3xl:fixed @3xl:sticky"></div>

{{-- 3xl responsive position classes --}}
<div class="3xl:static 3xl:relative 3xl:absolute 3xl:fixed 3xl:sticky"></div>

{{-- @4xl responsive position classes --}}
<div class="@4xl:static @4xl:relative @4xl:absolute @4xl:fixed @4xl:sticky"></div>

{{-- 4xl responsive position classes --}}
<div class="4xl:static 4xl:relative 4xl:absolute 4xl:fixed 4xl:sticky"></div>

{{-- @7xl responsive position classes --}}
<div class="@7xl:static @7xl:relative @7xl:absolute @7xl:fixed @7xl:sticky"></div>

{{-- 7xl responsive position classes --}}
<div class="7xl:static 7xl:relative 7xl:absolute 7xl:fixed 7xl:sticky"></div>

{{-- @3xl responsive position classes --}}
<div class="@3xl:static @3xl:relative @3xl:absolute @3xl:fixed @3xl:sticky"></div>

{{-- 3xl responsive position classes --}}
<div class="3xl:static 3xl:relative 3xl:absolute 3xl:fixed 3xl:sticky"></div>

{{-- @7xl responsive position classes --}}
<div class="@7xl:static @7xl:relative @7xl:absolute @7xl:fixed @7xl:sticky"></div>

{{-- 7xl responsive position classes --}}
<div class="7xl:static 7xl:relative 7xl:absolute 7xl:fixed 7xl:sticky"></div>
