{{-- Auto-generated Tailwind safe classes for font size --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}
<div style="display: none;">

    <!-- Font Size Classes -->
    <div class="text-xs text-sm text-base text-lg text-xl text-2xl text-3xl text-4xl text-5xl text-6xl text-7xl text-8xl text-9xl"></div>

    <!-- @3xl responsive font size classes -->
    <div class="@3xl:text-xs @3xl:text-sm @3xl:text-base @3xl:text-lg @3xl:text-xl @3xl:text-2xl @3xl:text-3xl @3xl:text-4xl @3xl:text-5xl @3xl:text-6xl @3xl:text-7xl @3xl:text-8xl @3xl:text-9xl"></div>

    <!-- @5xl responsive font size classes -->
    <div class="@5xl:text-xs @5xl:text-sm @5xl:text-base @5xl:text-lg @5xl:text-xl @5xl:text-2xl @5xl:text-3xl @5xl:text-4xl @5xl:text-5xl @5xl:text-6xl @5xl:text-7xl @5xl:text-8xl @5xl:text-9xl"></div>

    <!-- sm responsive font size classes -->
    <div class="sm:text-xs sm:text-sm sm:text-base sm:text-lg sm:text-xl sm:text-2xl sm:text-3xl sm:text-4xl sm:text-5xl sm:text-6xl sm:text-7xl sm:text-8xl sm:text-9xl"></div>

    <!-- md responsive font size classes -->
    <div class="md:text-xs md:text-sm md:text-base md:text-lg md:text-xl md:text-2xl md:text-3xl md:text-4xl md:text-5xl md:text-6xl md:text-7xl md:text-8xl md:text-9xl"></div>

    <!-- lg responsive font size classes -->
    <div class="lg:text-xs lg:text-sm lg:text-base lg:text-lg lg:text-xl lg:text-2xl lg:text-3xl lg:text-4xl lg:text-5xl lg:text-6xl lg:text-7xl lg:text-8xl lg:text-9xl"></div>

    <!-- xl responsive font size classes -->
    <div class="xl:text-xs xl:text-sm xl:text-base xl:text-lg xl:text-xl xl:text-2xl xl:text-3xl xl:text-4xl xl:text-5xl xl:text-6xl xl:text-7xl xl:text-8xl xl:text-9xl"></div>

    <!-- 2xl responsive font size classes -->
    <div class="2xl:text-xs 2xl:text-sm 2xl:text-base 2xl:text-lg 2xl:text-xl 2xl:text-2xl 2xl:text-3xl 2xl:text-4xl 2xl:text-5xl 2xl:text-6xl 2xl:text-7xl 2xl:text-8xl 2xl:text-9xl"></div>

</div>