{{-- Auto-generated Tailwind safe classes for grid --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Grid columns classes --}}
<div class="grid grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-5 grid-cols-6 grid-cols-7 grid-cols-8 grid-cols-9 grid-cols-10 grid-cols-11 grid-cols-12 grid-cols-13 grid-cols-14 grid-cols-15 grid-cols-16 grid-cols-17 grid-cols-18 grid-cols-19 grid-cols-20"></div>

{{-- Column span classes --}}
<div class="col-span-1 col-span-2 col-span-3 col-span-4 col-span-5 col-span-6 col-span-7 col-span-8 col-span-9 col-span-10 col-span-11 col-span-12 col-span-13 col-span-14 col-span-15 col-span-16 col-span-17 col-span-18 col-span-19 col-span-20"></div>

{{-- @3xl responsive grid classes --}}
<div class="@3xl:col-span-1 @3xl:col-span-2 @3xl:col-span-3 @3xl:col-span-4 @3xl:col-span-5 @3xl:col-span-6 @3xl:col-span-7 @3xl:col-span-8 @3xl:col-span-9 @3xl:col-span-10 @3xl:col-span-11 @3xl:col-span-12 @3xl:col-span-13 @3xl:col-span-14 @3xl:col-span-15 @3xl:col-span-16 @3xl:col-span-17 @3xl:col-span-18 @3xl:col-span-19 @3xl:col-span-20"></div>

{{-- @5xl responsive grid classes --}}
<div class="@5xl:col-span-1 @5xl:col-span-2 @5xl:col-span-3 @5xl:col-span-4 @5xl:col-span-5 @5xl:col-span-6 @5xl:col-span-7 @5xl:col-span-8 @5xl:col-span-9 @5xl:col-span-10 @5xl:col-span-11 @5xl:col-span-12 @5xl:col-span-13 @5xl:col-span-14 @5xl:col-span-15 @5xl:col-span-16 @5xl:col-span-17 @5xl:col-span-18 @5xl:col-span-19 @5xl:col-span-20"></div>
