{{-- Auto-generated Tailwind safe classes for colors --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Text color utilities --}}
<div class="text-gray-50 text-gray-100 text-gray-200 text-gray-300 text-gray-400 text-gray-500 text-gray-600 text-gray-700 text-gray-800 text-gray-900 text-red-300 text-red-400 text-red-500 text-red-600 text-red-700 text-blue-300 text-blue-400 text-blue-500 text-blue-600 text-blue-700 text-green-300 text-green-400 text-green-500 text-green-600 text-green-700 text-yellow-300 text-yellow-400 text-yellow-500 text-yellow-600 text-yellow-700 text-pink-300 text-pink-400 text-pink-500 text-pink-600 text-pink-700 text-purple-300 text-purple-400 text-purple-500 text-purple-600 text-purple-700 text-indigo-300 text-indigo-400 text-indigo-500 text-indigo-600 text-indigo-700"></div>

{{-- DaisyUI Theme Text Color Utilities --}}
<div class="text-base-100 text-base-200 text-base-300 text-base-content text-primary text-primary-content text-secondary text-secondary-content text-accent text-accent-content text-neutral text-neutral-content text-info text-info-content text-success text-success-content text-warning text-warning-content text-error text-error-content"></div>

{{-- Hover text color utilities --}}
<div class="hover:text-gray-50 hover:text-gray-100 hover:text-gray-200 hover:text-gray-300 hover:text-gray-400 hover:text-gray-500 hover:text-gray-600 hover:text-gray-700 hover:text-gray-800 hover:text-gray-900 hover:text-red-300 hover:text-red-400 hover:text-red-500 hover:text-red-600 hover:text-red-700 hover:text-blue-300 hover:text-blue-400 hover:text-blue-500 hover:text-blue-600 hover:text-blue-700 hover:text-green-300 hover:text-green-400 hover:text-green-500 hover:text-green-600 hover:text-green-700 hover:text-yellow-300 hover:text-yellow-400 hover:text-yellow-500 hover:text-yellow-600 hover:text-yellow-700 hover:text-pink-300 hover:text-pink-400 hover:text-pink-500 hover:text-pink-600 hover:text-pink-700 hover:text-purple-300 hover:text-purple-400 hover:text-purple-500 hover:text-purple-600 hover:text-purple-700 hover:text-indigo-300 hover:text-indigo-400 hover:text-indigo-500 hover:text-indigo-600 hover:text-indigo-700"></div>

{{-- DaisyUI Theme Hover Text Color Utilities --}}
<div class="hover:text-base-100 hover:text-base-200 hover:text-base-300 hover:text-base-content hover:text-primary hover:text-primary-content hover:text-secondary hover:text-secondary-content hover:text-accent hover:text-accent-content hover:text-neutral hover:text-neutral-content hover:text-info hover:text-info-content hover:text-success hover:text-success-content hover:text-warning hover:text-warning-content hover:text-error hover:text-error-content"></div>

{{-- Background color utilities --}}
<div class="bg-gray-50 bg-gray-100 bg-gray-200 bg-gray-300 bg-gray-400 bg-gray-500 bg-gray-600 bg-gray-700 bg-gray-800 bg-gray-900 bg-red-300 bg-red-400 bg-red-500 bg-red-600 bg-red-700 bg-blue-300 bg-blue-400 bg-blue-500 bg-blue-600 bg-blue-700 bg-green-300 bg-green-400 bg-green-500 bg-green-600 bg-green-700 bg-yellow-300 bg-yellow-400 bg-yellow-500 bg-yellow-600 bg-yellow-700 bg-pink-300 bg-pink-400 bg-pink-500 bg-pink-600 bg-pink-700 bg-purple-300 bg-purple-400 bg-purple-500 bg-purple-600 bg-purple-700 bg-indigo-300 bg-indigo-400 bg-indigo-500 bg-indigo-600 bg-indigo-700"></div>

{{-- DaisyUI Theme Background Color Utilities --}}
<div class="bg-base-100 bg-base-200 bg-base-300 bg-base-content bg-primary bg-primary-content bg-secondary bg-secondary-content bg-accent bg-accent-content bg-neutral bg-neutral-content bg-info bg-info-content bg-success bg-success-content bg-warning bg-warning-content bg-error bg-error-content"></div>

{{-- Hover background color utilities --}}
<div class="hover:bg-gray-50 hover:bg-gray-100 hover:bg-gray-200 hover:bg-gray-300 hover:bg-gray-400 hover:bg-gray-500 hover:bg-gray-600 hover:bg-gray-700 hover:bg-gray-800 hover:bg-gray-900 hover:bg-red-300 hover:bg-red-400 hover:bg-red-500 hover:bg-red-600 hover:bg-red-700 hover:bg-blue-300 hover:bg-blue-400 hover:bg-blue-500 hover:bg-blue-600 hover:bg-blue-700 hover:bg-green-300 hover:bg-green-400 hover:bg-green-500 hover:bg-green-600 hover:bg-green-700 hover:bg-yellow-300 hover:bg-yellow-400 hover:bg-yellow-500 hover:bg-yellow-600 hover:bg-yellow-700 hover:bg-pink-300 hover:bg-pink-400 hover:bg-pink-500 hover:bg-pink-600 hover:bg-pink-700 hover:bg-purple-300 hover:bg-purple-400 hover:bg-purple-500 hover:bg-purple-600 hover:bg-purple-700 hover:bg-indigo-300 hover:bg-indigo-400 hover:bg-indigo-500 hover:bg-indigo-600 hover:bg-indigo-700"></div>

{{-- DaisyUI Theme Hover Background Color Utilities --}}
<div class="hover:bg-base-100 hover:bg-base-200 hover:bg-base-300 hover:bg-base-content hover:bg-primary hover:bg-primary-content hover:bg-secondary hover:bg-secondary-content hover:bg-accent hover:bg-accent-content hover:bg-neutral hover:bg-neutral-content hover:bg-info hover:bg-info-content hover:bg-success hover:bg-success-content hover:bg-warning hover:bg-warning-content hover:bg-error hover:bg-error-content"></div>
