{{-- Auto-generated Tailwind safe classes for alignment --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Items alignment classes --}}
<div class="items-start items-center items-end items-baseline items-stretch"></div>

{{-- Justify content classes --}}
<div class="justify-start justify-center justify-end justify-between justify-around justify-evenly justify-stretch"></div>

{{-- Content alignment classes --}}
<div class="content-start content-center content-end content-baseline content-stretch"></div>

{{-- Layout classes --}}
<div class="container mx-auto md:container lg:container"></div>
