{{-- Auto-generated Tailwind safe classes for flex --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Flex classes --}}
<div class="flex flex-row flex-col"></div>

{{-- @3xl responsive flex classes --}}
<div class="@3xl:flex @3xl:flex-row @3xl:flex-col"></div>

{{-- @5xl responsive flex classes --}}
<div class="@5xl:flex @5xl:flex-row @5xl:flex-col"></div>
