{{-- Auto-generated Tailwind safe classes for margin --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Margin all classes --}}
<div class="m-0 m-px m-0.5 m-1 m-1.5 m-2 m-2.5 m-3 m-3.5 m-4 m-5 m-6 m-7 m-8 m-9 m-10 m-11 m-12 m-13 m-14 m-15 m-16 m-17 m-18 m-19 m-20 m-21 m-22 m-23 m-24 m-25 m-26 m-27 m-28 m-29 m-30 m-31 m-32 m-33 m-34 m-35 m-36 m-37 m-38 m-39 m-40"></div>

{{-- Negative margin all classes --}}
<div class="-m-px -m-0.5 -m-1 -m-1.5 -m-2 -m-2.5 -m-3 -m-3.5 -m-4 -m-5 -m-6 -m-7 -m-8 -m-9 -m-10 -m-11 -m-12 -m-13 -m-14 -m-15 -m-16 -m-17 -m-18 -m-19 -m-20 -m-21 -m-22 -m-23 -m-24 -m-25 -m-26 -m-27 -m-28 -m-29 -m-30 -m-31 -m-32 -m-33 -m-34 -m-35 -m-36 -m-37 -m-38 -m-39 -m-40"></div>

{{-- @3xl responsive margin all classes --}}
<div class="@3xl:m-0 @3xl:m-px @3xl:m-0.5 @3xl:m-1 @3xl:m-1.5 @3xl:m-2 @3xl:m-2.5 @3xl:m-3 @3xl:m-3.5 @3xl:m-4 @3xl:m-5 @3xl:m-6 @3xl:m-7 @3xl:m-8 @3xl:m-9 @3xl:m-10 @3xl:m-11 @3xl:m-12 @3xl:m-13 @3xl:m-14 @3xl:m-15 @3xl:m-16 @3xl:m-17 @3xl:m-18 @3xl:m-19 @3xl:m-20 @3xl:m-21 @3xl:m-22 @3xl:m-23 @3xl:m-24 @3xl:m-25 @3xl:m-26 @3xl:m-27 @3xl:m-28 @3xl:m-29 @3xl:m-30 @3xl:m-31 @3xl:m-32 @3xl:m-33 @3xl:m-34 @3xl:m-35 @3xl:m-36 @3xl:m-37 @3xl:m-38 @3xl:m-39 @3xl:m-40"></div>

{{-- @3xl responsive negative margin all classes --}}
<div class="@3xl:-m-px @3xl:-m-0.5 @3xl:-m-1 @3xl:-m-1.5 @3xl:-m-2 @3xl:-m-2.5 @3xl:-m-3 @3xl:-m-3.5 @3xl:-m-4 @3xl:-m-5 @3xl:-m-6 @3xl:-m-7 @3xl:-m-8 @3xl:-m-9 @3xl:-m-10 @3xl:-m-11 @3xl:-m-12 @3xl:-m-13 @3xl:-m-14 @3xl:-m-15 @3xl:-m-16 @3xl:-m-17 @3xl:-m-18 @3xl:-m-19 @3xl:-m-20 @3xl:-m-21 @3xl:-m-22 @3xl:-m-23 @3xl:-m-24 @3xl:-m-25 @3xl:-m-26 @3xl:-m-27 @3xl:-m-28 @3xl:-m-29 @3xl:-m-30 @3xl:-m-31 @3xl:-m-32 @3xl:-m-33 @3xl:-m-34 @3xl:-m-35 @3xl:-m-36 @3xl:-m-37 @3xl:-m-38 @3xl:-m-39 @3xl:-m-40"></div>

{{-- @5xl responsive margin all classes --}}
<div class="@5xl:m-0 @5xl:m-px @5xl:m-0.5 @5xl:m-1 @5xl:m-1.5 @5xl:m-2 @5xl:m-2.5 @5xl:m-3 @5xl:m-3.5 @5xl:m-4 @5xl:m-5 @5xl:m-6 @5xl:m-7 @5xl:m-8 @5xl:m-9 @5xl:m-10 @5xl:m-11 @5xl:m-12 @5xl:m-13 @5xl:m-14 @5xl:m-15 @5xl:m-16 @5xl:m-17 @5xl:m-18 @5xl:m-19 @5xl:m-20 @5xl:m-21 @5xl:m-22 @5xl:m-23 @5xl:m-24 @5xl:m-25 @5xl:m-26 @5xl:m-27 @5xl:m-28 @5xl:m-29 @5xl:m-30 @5xl:m-31 @5xl:m-32 @5xl:m-33 @5xl:m-34 @5xl:m-35 @5xl:m-36 @5xl:m-37 @5xl:m-38 @5xl:m-39 @5xl:m-40"></div>

{{-- @5xl responsive negative margin all classes --}}
<div class="@5xl:-m-px @5xl:-m-0.5 @5xl:-m-1 @5xl:-m-1.5 @5xl:-m-2 @5xl:-m-2.5 @5xl:-m-3 @5xl:-m-3.5 @5xl:-m-4 @5xl:-m-5 @5xl:-m-6 @5xl:-m-7 @5xl:-m-8 @5xl:-m-9 @5xl:-m-10 @5xl:-m-11 @5xl:-m-12 @5xl:-m-13 @5xl:-m-14 @5xl:-m-15 @5xl:-m-16 @5xl:-m-17 @5xl:-m-18 @5xl:-m-19 @5xl:-m-20 @5xl:-m-21 @5xl:-m-22 @5xl:-m-23 @5xl:-m-24 @5xl:-m-25 @5xl:-m-26 @5xl:-m-27 @5xl:-m-28 @5xl:-m-29 @5xl:-m-30 @5xl:-m-31 @5xl:-m-32 @5xl:-m-33 @5xl:-m-34 @5xl:-m-35 @5xl:-m-36 @5xl:-m-37 @5xl:-m-38 @5xl:-m-39 @5xl:-m-40"></div>

{{-- Margin top classes --}}
<div class="mt-0 mt-px mt-0.5 mt-1 mt-1.5 mt-2 mt-2.5 mt-3 mt-3.5 mt-4 mt-5 mt-6 mt-7 mt-8 mt-9 mt-10 mt-11 mt-12 mt-13 mt-14 mt-15 mt-16 mt-17 mt-18 mt-19 mt-20 mt-21 mt-22 mt-23 mt-24 mt-25 mt-26 mt-27 mt-28 mt-29 mt-30 mt-31 mt-32 mt-33 mt-34 mt-35 mt-36 mt-37 mt-38 mt-39 mt-40"></div>

{{-- Negative margin top classes --}}
<div class="-mt-px -mt-0.5 -mt-1 -mt-1.5 -mt-2 -mt-2.5 -mt-3 -mt-3.5 -mt-4 -mt-5 -mt-6 -mt-7 -mt-8 -mt-9 -mt-10 -mt-11 -mt-12 -mt-13 -mt-14 -mt-15 -mt-16 -mt-17 -mt-18 -mt-19 -mt-20 -mt-21 -mt-22 -mt-23 -mt-24 -mt-25 -mt-26 -mt-27 -mt-28 -mt-29 -mt-30 -mt-31 -mt-32 -mt-33 -mt-34 -mt-35 -mt-36 -mt-37 -mt-38 -mt-39 -mt-40"></div>

{{-- @3xl responsive margin top classes --}}
<div class="@3xl:mt-0 @3xl:mt-px @3xl:mt-0.5 @3xl:mt-1 @3xl:mt-1.5 @3xl:mt-2 @3xl:mt-2.5 @3xl:mt-3 @3xl:mt-3.5 @3xl:mt-4 @3xl:mt-5 @3xl:mt-6 @3xl:mt-7 @3xl:mt-8 @3xl:mt-9 @3xl:mt-10 @3xl:mt-11 @3xl:mt-12 @3xl:mt-13 @3xl:mt-14 @3xl:mt-15 @3xl:mt-16 @3xl:mt-17 @3xl:mt-18 @3xl:mt-19 @3xl:mt-20 @3xl:mt-21 @3xl:mt-22 @3xl:mt-23 @3xl:mt-24 @3xl:mt-25 @3xl:mt-26 @3xl:mt-27 @3xl:mt-28 @3xl:mt-29 @3xl:mt-30 @3xl:mt-31 @3xl:mt-32 @3xl:mt-33 @3xl:mt-34 @3xl:mt-35 @3xl:mt-36 @3xl:mt-37 @3xl:mt-38 @3xl:mt-39 @3xl:mt-40"></div>

{{-- @3xl responsive negative margin top classes --}}
<div class="@3xl:-mt-px @3xl:-mt-0.5 @3xl:-mt-1 @3xl:-mt-1.5 @3xl:-mt-2 @3xl:-mt-2.5 @3xl:-mt-3 @3xl:-mt-3.5 @3xl:-mt-4 @3xl:-mt-5 @3xl:-mt-6 @3xl:-mt-7 @3xl:-mt-8 @3xl:-mt-9 @3xl:-mt-10 @3xl:-mt-11 @3xl:-mt-12 @3xl:-mt-13 @3xl:-mt-14 @3xl:-mt-15 @3xl:-mt-16 @3xl:-mt-17 @3xl:-mt-18 @3xl:-mt-19 @3xl:-mt-20 @3xl:-mt-21 @3xl:-mt-22 @3xl:-mt-23 @3xl:-mt-24 @3xl:-mt-25 @3xl:-mt-26 @3xl:-mt-27 @3xl:-mt-28 @3xl:-mt-29 @3xl:-mt-30 @3xl:-mt-31 @3xl:-mt-32 @3xl:-mt-33 @3xl:-mt-34 @3xl:-mt-35 @3xl:-mt-36 @3xl:-mt-37 @3xl:-mt-38 @3xl:-mt-39 @3xl:-mt-40"></div>

{{-- @5xl responsive margin top classes --}}
<div class="@5xl:mt-0 @5xl:mt-px @5xl:mt-0.5 @5xl:mt-1 @5xl:mt-1.5 @5xl:mt-2 @5xl:mt-2.5 @5xl:mt-3 @5xl:mt-3.5 @5xl:mt-4 @5xl:mt-5 @5xl:mt-6 @5xl:mt-7 @5xl:mt-8 @5xl:mt-9 @5xl:mt-10 @5xl:mt-11 @5xl:mt-12 @5xl:mt-13 @5xl:mt-14 @5xl:mt-15 @5xl:mt-16 @5xl:mt-17 @5xl:mt-18 @5xl:mt-19 @5xl:mt-20 @5xl:mt-21 @5xl:mt-22 @5xl:mt-23 @5xl:mt-24 @5xl:mt-25 @5xl:mt-26 @5xl:mt-27 @5xl:mt-28 @5xl:mt-29 @5xl:mt-30 @5xl:mt-31 @5xl:mt-32 @5xl:mt-33 @5xl:mt-34 @5xl:mt-35 @5xl:mt-36 @5xl:mt-37 @5xl:mt-38 @5xl:mt-39 @5xl:mt-40"></div>

{{-- @5xl responsive negative margin top classes --}}
<div class="@5xl:-mt-px @5xl:-mt-0.5 @5xl:-mt-1 @5xl:-mt-1.5 @5xl:-mt-2 @5xl:-mt-2.5 @5xl:-mt-3 @5xl:-mt-3.5 @5xl:-mt-4 @5xl:-mt-5 @5xl:-mt-6 @5xl:-mt-7 @5xl:-mt-8 @5xl:-mt-9 @5xl:-mt-10 @5xl:-mt-11 @5xl:-mt-12 @5xl:-mt-13 @5xl:-mt-14 @5xl:-mt-15 @5xl:-mt-16 @5xl:-mt-17 @5xl:-mt-18 @5xl:-mt-19 @5xl:-mt-20 @5xl:-mt-21 @5xl:-mt-22 @5xl:-mt-23 @5xl:-mt-24 @5xl:-mt-25 @5xl:-mt-26 @5xl:-mt-27 @5xl:-mt-28 @5xl:-mt-29 @5xl:-mt-30 @5xl:-mt-31 @5xl:-mt-32 @5xl:-mt-33 @5xl:-mt-34 @5xl:-mt-35 @5xl:-mt-36 @5xl:-mt-37 @5xl:-mt-38 @5xl:-mt-39 @5xl:-mt-40"></div>

{{-- Margin right classes --}}
<div class="mr-0 mr-px mr-0.5 mr-1 mr-1.5 mr-2 mr-2.5 mr-3 mr-3.5 mr-4 mr-5 mr-6 mr-7 mr-8 mr-9 mr-10 mr-11 mr-12 mr-13 mr-14 mr-15 mr-16 mr-17 mr-18 mr-19 mr-20 mr-21 mr-22 mr-23 mr-24 mr-25 mr-26 mr-27 mr-28 mr-29 mr-30 mr-31 mr-32 mr-33 mr-34 mr-35 mr-36 mr-37 mr-38 mr-39 mr-40"></div>

{{-- Negative margin right classes --}}
<div class="-mr-px -mr-0.5 -mr-1 -mr-1.5 -mr-2 -mr-2.5 -mr-3 -mr-3.5 -mr-4 -mr-5 -mr-6 -mr-7 -mr-8 -mr-9 -mr-10 -mr-11 -mr-12 -mr-13 -mr-14 -mr-15 -mr-16 -mr-17 -mr-18 -mr-19 -mr-20 -mr-21 -mr-22 -mr-23 -mr-24 -mr-25 -mr-26 -mr-27 -mr-28 -mr-29 -mr-30 -mr-31 -mr-32 -mr-33 -mr-34 -mr-35 -mr-36 -mr-37 -mr-38 -mr-39 -mr-40"></div>

{{-- @3xl responsive margin right classes --}}
<div class="@3xl:mr-0 @3xl:mr-px @3xl:mr-0.5 @3xl:mr-1 @3xl:mr-1.5 @3xl:mr-2 @3xl:mr-2.5 @3xl:mr-3 @3xl:mr-3.5 @3xl:mr-4 @3xl:mr-5 @3xl:mr-6 @3xl:mr-7 @3xl:mr-8 @3xl:mr-9 @3xl:mr-10 @3xl:mr-11 @3xl:mr-12 @3xl:mr-13 @3xl:mr-14 @3xl:mr-15 @3xl:mr-16 @3xl:mr-17 @3xl:mr-18 @3xl:mr-19 @3xl:mr-20 @3xl:mr-21 @3xl:mr-22 @3xl:mr-23 @3xl:mr-24 @3xl:mr-25 @3xl:mr-26 @3xl:mr-27 @3xl:mr-28 @3xl:mr-29 @3xl:mr-30 @3xl:mr-31 @3xl:mr-32 @3xl:mr-33 @3xl:mr-34 @3xl:mr-35 @3xl:mr-36 @3xl:mr-37 @3xl:mr-38 @3xl:mr-39 @3xl:mr-40"></div>

{{-- @3xl responsive negative margin right classes --}}
<div class="@3xl:-mr-px @3xl:-mr-0.5 @3xl:-mr-1 @3xl:-mr-1.5 @3xl:-mr-2 @3xl:-mr-2.5 @3xl:-mr-3 @3xl:-mr-3.5 @3xl:-mr-4 @3xl:-mr-5 @3xl:-mr-6 @3xl:-mr-7 @3xl:-mr-8 @3xl:-mr-9 @3xl:-mr-10 @3xl:-mr-11 @3xl:-mr-12 @3xl:-mr-13 @3xl:-mr-14 @3xl:-mr-15 @3xl:-mr-16 @3xl:-mr-17 @3xl:-mr-18 @3xl:-mr-19 @3xl:-mr-20 @3xl:-mr-21 @3xl:-mr-22 @3xl:-mr-23 @3xl:-mr-24 @3xl:-mr-25 @3xl:-mr-26 @3xl:-mr-27 @3xl:-mr-28 @3xl:-mr-29 @3xl:-mr-30 @3xl:-mr-31 @3xl:-mr-32 @3xl:-mr-33 @3xl:-mr-34 @3xl:-mr-35 @3xl:-mr-36 @3xl:-mr-37 @3xl:-mr-38 @3xl:-mr-39 @3xl:-mr-40"></div>

{{-- @5xl responsive margin right classes --}}
<div class="@5xl:mr-0 @5xl:mr-px @5xl:mr-0.5 @5xl:mr-1 @5xl:mr-1.5 @5xl:mr-2 @5xl:mr-2.5 @5xl:mr-3 @5xl:mr-3.5 @5xl:mr-4 @5xl:mr-5 @5xl:mr-6 @5xl:mr-7 @5xl:mr-8 @5xl:mr-9 @5xl:mr-10 @5xl:mr-11 @5xl:mr-12 @5xl:mr-13 @5xl:mr-14 @5xl:mr-15 @5xl:mr-16 @5xl:mr-17 @5xl:mr-18 @5xl:mr-19 @5xl:mr-20 @5xl:mr-21 @5xl:mr-22 @5xl:mr-23 @5xl:mr-24 @5xl:mr-25 @5xl:mr-26 @5xl:mr-27 @5xl:mr-28 @5xl:mr-29 @5xl:mr-30 @5xl:mr-31 @5xl:mr-32 @5xl:mr-33 @5xl:mr-34 @5xl:mr-35 @5xl:mr-36 @5xl:mr-37 @5xl:mr-38 @5xl:mr-39 @5xl:mr-40"></div>

{{-- @5xl responsive negative margin right classes --}}
<div class="@5xl:-mr-px @5xl:-mr-0.5 @5xl:-mr-1 @5xl:-mr-1.5 @5xl:-mr-2 @5xl:-mr-2.5 @5xl:-mr-3 @5xl:-mr-3.5 @5xl:-mr-4 @5xl:-mr-5 @5xl:-mr-6 @5xl:-mr-7 @5xl:-mr-8 @5xl:-mr-9 @5xl:-mr-10 @5xl:-mr-11 @5xl:-mr-12 @5xl:-mr-13 @5xl:-mr-14 @5xl:-mr-15 @5xl:-mr-16 @5xl:-mr-17 @5xl:-mr-18 @5xl:-mr-19 @5xl:-mr-20 @5xl:-mr-21 @5xl:-mr-22 @5xl:-mr-23 @5xl:-mr-24 @5xl:-mr-25 @5xl:-mr-26 @5xl:-mr-27 @5xl:-mr-28 @5xl:-mr-29 @5xl:-mr-30 @5xl:-mr-31 @5xl:-mr-32 @5xl:-mr-33 @5xl:-mr-34 @5xl:-mr-35 @5xl:-mr-36 @5xl:-mr-37 @5xl:-mr-38 @5xl:-mr-39 @5xl:-mr-40"></div>

{{-- Margin bottom classes --}}
<div class="mb-0 mb-px mb-0.5 mb-1 mb-1.5 mb-2 mb-2.5 mb-3 mb-3.5 mb-4 mb-5 mb-6 mb-7 mb-8 mb-9 mb-10 mb-11 mb-12 mb-13 mb-14 mb-15 mb-16 mb-17 mb-18 mb-19 mb-20 mb-21 mb-22 mb-23 mb-24 mb-25 mb-26 mb-27 mb-28 mb-29 mb-30 mb-31 mb-32 mb-33 mb-34 mb-35 mb-36 mb-37 mb-38 mb-39 mb-40"></div>

{{-- Negative margin bottom classes --}}
<div class="-mb-px -mb-0.5 -mb-1 -mb-1.5 -mb-2 -mb-2.5 -mb-3 -mb-3.5 -mb-4 -mb-5 -mb-6 -mb-7 -mb-8 -mb-9 -mb-10 -mb-11 -mb-12 -mb-13 -mb-14 -mb-15 -mb-16 -mb-17 -mb-18 -mb-19 -mb-20 -mb-21 -mb-22 -mb-23 -mb-24 -mb-25 -mb-26 -mb-27 -mb-28 -mb-29 -mb-30 -mb-31 -mb-32 -mb-33 -mb-34 -mb-35 -mb-36 -mb-37 -mb-38 -mb-39 -mb-40"></div>

{{-- @3xl responsive margin bottom classes --}}
<div class="@3xl:mb-0 @3xl:mb-px @3xl:mb-0.5 @3xl:mb-1 @3xl:mb-1.5 @3xl:mb-2 @3xl:mb-2.5 @3xl:mb-3 @3xl:mb-3.5 @3xl:mb-4 @3xl:mb-5 @3xl:mb-6 @3xl:mb-7 @3xl:mb-8 @3xl:mb-9 @3xl:mb-10 @3xl:mb-11 @3xl:mb-12 @3xl:mb-13 @3xl:mb-14 @3xl:mb-15 @3xl:mb-16 @3xl:mb-17 @3xl:mb-18 @3xl:mb-19 @3xl:mb-20 @3xl:mb-21 @3xl:mb-22 @3xl:mb-23 @3xl:mb-24 @3xl:mb-25 @3xl:mb-26 @3xl:mb-27 @3xl:mb-28 @3xl:mb-29 @3xl:mb-30 @3xl:mb-31 @3xl:mb-32 @3xl:mb-33 @3xl:mb-34 @3xl:mb-35 @3xl:mb-36 @3xl:mb-37 @3xl:mb-38 @3xl:mb-39 @3xl:mb-40"></div>

{{-- @3xl responsive negative margin bottom classes --}}
<div class="@3xl:-mb-px @3xl:-mb-0.5 @3xl:-mb-1 @3xl:-mb-1.5 @3xl:-mb-2 @3xl:-mb-2.5 @3xl:-mb-3 @3xl:-mb-3.5 @3xl:-mb-4 @3xl:-mb-5 @3xl:-mb-6 @3xl:-mb-7 @3xl:-mb-8 @3xl:-mb-9 @3xl:-mb-10 @3xl:-mb-11 @3xl:-mb-12 @3xl:-mb-13 @3xl:-mb-14 @3xl:-mb-15 @3xl:-mb-16 @3xl:-mb-17 @3xl:-mb-18 @3xl:-mb-19 @3xl:-mb-20 @3xl:-mb-21 @3xl:-mb-22 @3xl:-mb-23 @3xl:-mb-24 @3xl:-mb-25 @3xl:-mb-26 @3xl:-mb-27 @3xl:-mb-28 @3xl:-mb-29 @3xl:-mb-30 @3xl:-mb-31 @3xl:-mb-32 @3xl:-mb-33 @3xl:-mb-34 @3xl:-mb-35 @3xl:-mb-36 @3xl:-mb-37 @3xl:-mb-38 @3xl:-mb-39 @3xl:-mb-40"></div>

{{-- @5xl responsive margin bottom classes --}}
<div class="@5xl:mb-0 @5xl:mb-px @5xl:mb-0.5 @5xl:mb-1 @5xl:mb-1.5 @5xl:mb-2 @5xl:mb-2.5 @5xl:mb-3 @5xl:mb-3.5 @5xl:mb-4 @5xl:mb-5 @5xl:mb-6 @5xl:mb-7 @5xl:mb-8 @5xl:mb-9 @5xl:mb-10 @5xl:mb-11 @5xl:mb-12 @5xl:mb-13 @5xl:mb-14 @5xl:mb-15 @5xl:mb-16 @5xl:mb-17 @5xl:mb-18 @5xl:mb-19 @5xl:mb-20 @5xl:mb-21 @5xl:mb-22 @5xl:mb-23 @5xl:mb-24 @5xl:mb-25 @5xl:mb-26 @5xl:mb-27 @5xl:mb-28 @5xl:mb-29 @5xl:mb-30 @5xl:mb-31 @5xl:mb-32 @5xl:mb-33 @5xl:mb-34 @5xl:mb-35 @5xl:mb-36 @5xl:mb-37 @5xl:mb-38 @5xl:mb-39 @5xl:mb-40"></div>

{{-- @5xl responsive negative margin bottom classes --}}
<div class="@5xl:-mb-px @5xl:-mb-0.5 @5xl:-mb-1 @5xl:-mb-1.5 @5xl:-mb-2 @5xl:-mb-2.5 @5xl:-mb-3 @5xl:-mb-3.5 @5xl:-mb-4 @5xl:-mb-5 @5xl:-mb-6 @5xl:-mb-7 @5xl:-mb-8 @5xl:-mb-9 @5xl:-mb-10 @5xl:-mb-11 @5xl:-mb-12 @5xl:-mb-13 @5xl:-mb-14 @5xl:-mb-15 @5xl:-mb-16 @5xl:-mb-17 @5xl:-mb-18 @5xl:-mb-19 @5xl:-mb-20 @5xl:-mb-21 @5xl:-mb-22 @5xl:-mb-23 @5xl:-mb-24 @5xl:-mb-25 @5xl:-mb-26 @5xl:-mb-27 @5xl:-mb-28 @5xl:-mb-29 @5xl:-mb-30 @5xl:-mb-31 @5xl:-mb-32 @5xl:-mb-33 @5xl:-mb-34 @5xl:-mb-35 @5xl:-mb-36 @5xl:-mb-37 @5xl:-mb-38 @5xl:-mb-39 @5xl:-mb-40"></div>

{{-- Margin left classes --}}
<div class="ml-0 ml-px ml-0.5 ml-1 ml-1.5 ml-2 ml-2.5 ml-3 ml-3.5 ml-4 ml-5 ml-6 ml-7 ml-8 ml-9 ml-10 ml-11 ml-12 ml-13 ml-14 ml-15 ml-16 ml-17 ml-18 ml-19 ml-20 ml-21 ml-22 ml-23 ml-24 ml-25 ml-26 ml-27 ml-28 ml-29 ml-30 ml-31 ml-32 ml-33 ml-34 ml-35 ml-36 ml-37 ml-38 ml-39 ml-40"></div>

{{-- Negative margin left classes --}}
<div class="-ml-px -ml-0.5 -ml-1 -ml-1.5 -ml-2 -ml-2.5 -ml-3 -ml-3.5 -ml-4 -ml-5 -ml-6 -ml-7 -ml-8 -ml-9 -ml-10 -ml-11 -ml-12 -ml-13 -ml-14 -ml-15 -ml-16 -ml-17 -ml-18 -ml-19 -ml-20 -ml-21 -ml-22 -ml-23 -ml-24 -ml-25 -ml-26 -ml-27 -ml-28 -ml-29 -ml-30 -ml-31 -ml-32 -ml-33 -ml-34 -ml-35 -ml-36 -ml-37 -ml-38 -ml-39 -ml-40"></div>

{{-- @3xl responsive margin left classes --}}
<div class="@3xl:ml-0 @3xl:ml-px @3xl:ml-0.5 @3xl:ml-1 @3xl:ml-1.5 @3xl:ml-2 @3xl:ml-2.5 @3xl:ml-3 @3xl:ml-3.5 @3xl:ml-4 @3xl:ml-5 @3xl:ml-6 @3xl:ml-7 @3xl:ml-8 @3xl:ml-9 @3xl:ml-10 @3xl:ml-11 @3xl:ml-12 @3xl:ml-13 @3xl:ml-14 @3xl:ml-15 @3xl:ml-16 @3xl:ml-17 @3xl:ml-18 @3xl:ml-19 @3xl:ml-20 @3xl:ml-21 @3xl:ml-22 @3xl:ml-23 @3xl:ml-24 @3xl:ml-25 @3xl:ml-26 @3xl:ml-27 @3xl:ml-28 @3xl:ml-29 @3xl:ml-30 @3xl:ml-31 @3xl:ml-32 @3xl:ml-33 @3xl:ml-34 @3xl:ml-35 @3xl:ml-36 @3xl:ml-37 @3xl:ml-38 @3xl:ml-39 @3xl:ml-40"></div>

{{-- @3xl responsive negative margin left classes --}}
<div class="@3xl:-ml-px @3xl:-ml-0.5 @3xl:-ml-1 @3xl:-ml-1.5 @3xl:-ml-2 @3xl:-ml-2.5 @3xl:-ml-3 @3xl:-ml-3.5 @3xl:-ml-4 @3xl:-ml-5 @3xl:-ml-6 @3xl:-ml-7 @3xl:-ml-8 @3xl:-ml-9 @3xl:-ml-10 @3xl:-ml-11 @3xl:-ml-12 @3xl:-ml-13 @3xl:-ml-14 @3xl:-ml-15 @3xl:-ml-16 @3xl:-ml-17 @3xl:-ml-18 @3xl:-ml-19 @3xl:-ml-20 @3xl:-ml-21 @3xl:-ml-22 @3xl:-ml-23 @3xl:-ml-24 @3xl:-ml-25 @3xl:-ml-26 @3xl:-ml-27 @3xl:-ml-28 @3xl:-ml-29 @3xl:-ml-30 @3xl:-ml-31 @3xl:-ml-32 @3xl:-ml-33 @3xl:-ml-34 @3xl:-ml-35 @3xl:-ml-36 @3xl:-ml-37 @3xl:-ml-38 @3xl:-ml-39 @3xl:-ml-40"></div>

{{-- @5xl responsive margin left classes --}}
<div class="@5xl:ml-0 @5xl:ml-px @5xl:ml-0.5 @5xl:ml-1 @5xl:ml-1.5 @5xl:ml-2 @5xl:ml-2.5 @5xl:ml-3 @5xl:ml-3.5 @5xl:ml-4 @5xl:ml-5 @5xl:ml-6 @5xl:ml-7 @5xl:ml-8 @5xl:ml-9 @5xl:ml-10 @5xl:ml-11 @5xl:ml-12 @5xl:ml-13 @5xl:ml-14 @5xl:ml-15 @5xl:ml-16 @5xl:ml-17 @5xl:ml-18 @5xl:ml-19 @5xl:ml-20 @5xl:ml-21 @5xl:ml-22 @5xl:ml-23 @5xl:ml-24 @5xl:ml-25 @5xl:ml-26 @5xl:ml-27 @5xl:ml-28 @5xl:ml-29 @5xl:ml-30 @5xl:ml-31 @5xl:ml-32 @5xl:ml-33 @5xl:ml-34 @5xl:ml-35 @5xl:ml-36 @5xl:ml-37 @5xl:ml-38 @5xl:ml-39 @5xl:ml-40"></div>

{{-- @5xl responsive negative margin left classes --}}
<div class="@5xl:-ml-px @5xl:-ml-0.5 @5xl:-ml-1 @5xl:-ml-1.5 @5xl:-ml-2 @5xl:-ml-2.5 @5xl:-ml-3 @5xl:-ml-3.5 @5xl:-ml-4 @5xl:-ml-5 @5xl:-ml-6 @5xl:-ml-7 @5xl:-ml-8 @5xl:-ml-9 @5xl:-ml-10 @5xl:-ml-11 @5xl:-ml-12 @5xl:-ml-13 @5xl:-ml-14 @5xl:-ml-15 @5xl:-ml-16 @5xl:-ml-17 @5xl:-ml-18 @5xl:-ml-19 @5xl:-ml-20 @5xl:-ml-21 @5xl:-ml-22 @5xl:-ml-23 @5xl:-ml-24 @5xl:-ml-25 @5xl:-ml-26 @5xl:-ml-27 @5xl:-ml-28 @5xl:-ml-29 @5xl:-ml-30 @5xl:-ml-31 @5xl:-ml-32 @5xl:-ml-33 @5xl:-ml-34 @5xl:-ml-35 @5xl:-ml-36 @5xl:-ml-37 @5xl:-ml-38 @5xl:-ml-39 @5xl:-ml-40"></div>

{{-- Margin horizontal classes --}}
<div class="mx-0 mx-px mx-0.5 mx-1 mx-1.5 mx-2 mx-2.5 mx-3 mx-3.5 mx-4 mx-5 mx-6 mx-7 mx-8 mx-9 mx-10 mx-11 mx-12 mx-13 mx-14 mx-15 mx-16 mx-17 mx-18 mx-19 mx-20 mx-21 mx-22 mx-23 mx-24 mx-25 mx-26 mx-27 mx-28 mx-29 mx-30 mx-31 mx-32 mx-33 mx-34 mx-35 mx-36 mx-37 mx-38 mx-39 mx-40"></div>

{{-- Negative margin horizontal classes --}}
<div class="-mx-px -mx-0.5 -mx-1 -mx-1.5 -mx-2 -mx-2.5 -mx-3 -mx-3.5 -mx-4 -mx-5 -mx-6 -mx-7 -mx-8 -mx-9 -mx-10 -mx-11 -mx-12 -mx-13 -mx-14 -mx-15 -mx-16 -mx-17 -mx-18 -mx-19 -mx-20 -mx-21 -mx-22 -mx-23 -mx-24 -mx-25 -mx-26 -mx-27 -mx-28 -mx-29 -mx-30 -mx-31 -mx-32 -mx-33 -mx-34 -mx-35 -mx-36 -mx-37 -mx-38 -mx-39 -mx-40"></div>

{{-- @3xl responsive margin horizontal classes --}}
<div class="@3xl:mx-0 @3xl:mx-px @3xl:mx-0.5 @3xl:mx-1 @3xl:mx-1.5 @3xl:mx-2 @3xl:mx-2.5 @3xl:mx-3 @3xl:mx-3.5 @3xl:mx-4 @3xl:mx-5 @3xl:mx-6 @3xl:mx-7 @3xl:mx-8 @3xl:mx-9 @3xl:mx-10 @3xl:mx-11 @3xl:mx-12 @3xl:mx-13 @3xl:mx-14 @3xl:mx-15 @3xl:mx-16 @3xl:mx-17 @3xl:mx-18 @3xl:mx-19 @3xl:mx-20 @3xl:mx-21 @3xl:mx-22 @3xl:mx-23 @3xl:mx-24 @3xl:mx-25 @3xl:mx-26 @3xl:mx-27 @3xl:mx-28 @3xl:mx-29 @3xl:mx-30 @3xl:mx-31 @3xl:mx-32 @3xl:mx-33 @3xl:mx-34 @3xl:mx-35 @3xl:mx-36 @3xl:mx-37 @3xl:mx-38 @3xl:mx-39 @3xl:mx-40"></div>

{{-- @3xl responsive negative margin horizontal classes --}}
<div class="@3xl:-mx-px @3xl:-mx-0.5 @3xl:-mx-1 @3xl:-mx-1.5 @3xl:-mx-2 @3xl:-mx-2.5 @3xl:-mx-3 @3xl:-mx-3.5 @3xl:-mx-4 @3xl:-mx-5 @3xl:-mx-6 @3xl:-mx-7 @3xl:-mx-8 @3xl:-mx-9 @3xl:-mx-10 @3xl:-mx-11 @3xl:-mx-12 @3xl:-mx-13 @3xl:-mx-14 @3xl:-mx-15 @3xl:-mx-16 @3xl:-mx-17 @3xl:-mx-18 @3xl:-mx-19 @3xl:-mx-20 @3xl:-mx-21 @3xl:-mx-22 @3xl:-mx-23 @3xl:-mx-24 @3xl:-mx-25 @3xl:-mx-26 @3xl:-mx-27 @3xl:-mx-28 @3xl:-mx-29 @3xl:-mx-30 @3xl:-mx-31 @3xl:-mx-32 @3xl:-mx-33 @3xl:-mx-34 @3xl:-mx-35 @3xl:-mx-36 @3xl:-mx-37 @3xl:-mx-38 @3xl:-mx-39 @3xl:-mx-40"></div>

{{-- @5xl responsive margin horizontal classes --}}
<div class="@5xl:mx-0 @5xl:mx-px @5xl:mx-0.5 @5xl:mx-1 @5xl:mx-1.5 @5xl:mx-2 @5xl:mx-2.5 @5xl:mx-3 @5xl:mx-3.5 @5xl:mx-4 @5xl:mx-5 @5xl:mx-6 @5xl:mx-7 @5xl:mx-8 @5xl:mx-9 @5xl:mx-10 @5xl:mx-11 @5xl:mx-12 @5xl:mx-13 @5xl:mx-14 @5xl:mx-15 @5xl:mx-16 @5xl:mx-17 @5xl:mx-18 @5xl:mx-19 @5xl:mx-20 @5xl:mx-21 @5xl:mx-22 @5xl:mx-23 @5xl:mx-24 @5xl:mx-25 @5xl:mx-26 @5xl:mx-27 @5xl:mx-28 @5xl:mx-29 @5xl:mx-30 @5xl:mx-31 @5xl:mx-32 @5xl:mx-33 @5xl:mx-34 @5xl:mx-35 @5xl:mx-36 @5xl:mx-37 @5xl:mx-38 @5xl:mx-39 @5xl:mx-40"></div>

{{-- @5xl responsive negative margin horizontal classes --}}
<div class="@5xl:-mx-px @5xl:-mx-0.5 @5xl:-mx-1 @5xl:-mx-1.5 @5xl:-mx-2 @5xl:-mx-2.5 @5xl:-mx-3 @5xl:-mx-3.5 @5xl:-mx-4 @5xl:-mx-5 @5xl:-mx-6 @5xl:-mx-7 @5xl:-mx-8 @5xl:-mx-9 @5xl:-mx-10 @5xl:-mx-11 @5xl:-mx-12 @5xl:-mx-13 @5xl:-mx-14 @5xl:-mx-15 @5xl:-mx-16 @5xl:-mx-17 @5xl:-mx-18 @5xl:-mx-19 @5xl:-mx-20 @5xl:-mx-21 @5xl:-mx-22 @5xl:-mx-23 @5xl:-mx-24 @5xl:-mx-25 @5xl:-mx-26 @5xl:-mx-27 @5xl:-mx-28 @5xl:-mx-29 @5xl:-mx-30 @5xl:-mx-31 @5xl:-mx-32 @5xl:-mx-33 @5xl:-mx-34 @5xl:-mx-35 @5xl:-mx-36 @5xl:-mx-37 @5xl:-mx-38 @5xl:-mx-39 @5xl:-mx-40"></div>

{{-- Margin vertical classes --}}
<div class="my-0 my-px my-0.5 my-1 my-1.5 my-2 my-2.5 my-3 my-3.5 my-4 my-5 my-6 my-7 my-8 my-9 my-10 my-11 my-12 my-13 my-14 my-15 my-16 my-17 my-18 my-19 my-20 my-21 my-22 my-23 my-24 my-25 my-26 my-27 my-28 my-29 my-30 my-31 my-32 my-33 my-34 my-35 my-36 my-37 my-38 my-39 my-40"></div>

{{-- Negative margin vertical classes --}}
<div class="-my-px -my-0.5 -my-1 -my-1.5 -my-2 -my-2.5 -my-3 -my-3.5 -my-4 -my-5 -my-6 -my-7 -my-8 -my-9 -my-10 -my-11 -my-12 -my-13 -my-14 -my-15 -my-16 -my-17 -my-18 -my-19 -my-20 -my-21 -my-22 -my-23 -my-24 -my-25 -my-26 -my-27 -my-28 -my-29 -my-30 -my-31 -my-32 -my-33 -my-34 -my-35 -my-36 -my-37 -my-38 -my-39 -my-40"></div>

{{-- @3xl responsive margin vertical classes --}}
<div class="@3xl:my-0 @3xl:my-px @3xl:my-0.5 @3xl:my-1 @3xl:my-1.5 @3xl:my-2 @3xl:my-2.5 @3xl:my-3 @3xl:my-3.5 @3xl:my-4 @3xl:my-5 @3xl:my-6 @3xl:my-7 @3xl:my-8 @3xl:my-9 @3xl:my-10 @3xl:my-11 @3xl:my-12 @3xl:my-13 @3xl:my-14 @3xl:my-15 @3xl:my-16 @3xl:my-17 @3xl:my-18 @3xl:my-19 @3xl:my-20 @3xl:my-21 @3xl:my-22 @3xl:my-23 @3xl:my-24 @3xl:my-25 @3xl:my-26 @3xl:my-27 @3xl:my-28 @3xl:my-29 @3xl:my-30 @3xl:my-31 @3xl:my-32 @3xl:my-33 @3xl:my-34 @3xl:my-35 @3xl:my-36 @3xl:my-37 @3xl:my-38 @3xl:my-39 @3xl:my-40"></div>

{{-- @3xl responsive negative margin vertical classes --}}
<div class="@3xl:-my-px @3xl:-my-0.5 @3xl:-my-1 @3xl:-my-1.5 @3xl:-my-2 @3xl:-my-2.5 @3xl:-my-3 @3xl:-my-3.5 @3xl:-my-4 @3xl:-my-5 @3xl:-my-6 @3xl:-my-7 @3xl:-my-8 @3xl:-my-9 @3xl:-my-10 @3xl:-my-11 @3xl:-my-12 @3xl:-my-13 @3xl:-my-14 @3xl:-my-15 @3xl:-my-16 @3xl:-my-17 @3xl:-my-18 @3xl:-my-19 @3xl:-my-20 @3xl:-my-21 @3xl:-my-22 @3xl:-my-23 @3xl:-my-24 @3xl:-my-25 @3xl:-my-26 @3xl:-my-27 @3xl:-my-28 @3xl:-my-29 @3xl:-my-30 @3xl:-my-31 @3xl:-my-32 @3xl:-my-33 @3xl:-my-34 @3xl:-my-35 @3xl:-my-36 @3xl:-my-37 @3xl:-my-38 @3xl:-my-39 @3xl:-my-40"></div>

{{-- @5xl responsive margin vertical classes --}}
<div class="@5xl:my-0 @5xl:my-px @5xl:my-0.5 @5xl:my-1 @5xl:my-1.5 @5xl:my-2 @5xl:my-2.5 @5xl:my-3 @5xl:my-3.5 @5xl:my-4 @5xl:my-5 @5xl:my-6 @5xl:my-7 @5xl:my-8 @5xl:my-9 @5xl:my-10 @5xl:my-11 @5xl:my-12 @5xl:my-13 @5xl:my-14 @5xl:my-15 @5xl:my-16 @5xl:my-17 @5xl:my-18 @5xl:my-19 @5xl:my-20 @5xl:my-21 @5xl:my-22 @5xl:my-23 @5xl:my-24 @5xl:my-25 @5xl:my-26 @5xl:my-27 @5xl:my-28 @5xl:my-29 @5xl:my-30 @5xl:my-31 @5xl:my-32 @5xl:my-33 @5xl:my-34 @5xl:my-35 @5xl:my-36 @5xl:my-37 @5xl:my-38 @5xl:my-39 @5xl:my-40"></div>

{{-- @5xl responsive negative margin vertical classes --}}
<div class="@5xl:-my-px @5xl:-my-0.5 @5xl:-my-1 @5xl:-my-1.5 @5xl:-my-2 @5xl:-my-2.5 @5xl:-my-3 @5xl:-my-3.5 @5xl:-my-4 @5xl:-my-5 @5xl:-my-6 @5xl:-my-7 @5xl:-my-8 @5xl:-my-9 @5xl:-my-10 @5xl:-my-11 @5xl:-my-12 @5xl:-my-13 @5xl:-my-14 @5xl:-my-15 @5xl:-my-16 @5xl:-my-17 @5xl:-my-18 @5xl:-my-19 @5xl:-my-20 @5xl:-my-21 @5xl:-my-22 @5xl:-my-23 @5xl:-my-24 @5xl:-my-25 @5xl:-my-26 @5xl:-my-27 @5xl:-my-28 @5xl:-my-29 @5xl:-my-30 @5xl:-my-31 @5xl:-my-32 @5xl:-my-33 @5xl:-my-34 @5xl:-my-35 @5xl:-my-36 @5xl:-my-37 @5xl:-my-38 @5xl:-my-39 @5xl:-my-40"></div>
