{{-- Auto-generated Tailwind safe classes for gap --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Gap classes --}}
<div class="gap-0 gap-1 gap-2 gap-3 gap-4 gap-5 gap-6 gap-7 gap-8 gap-9 gap-10 gap-11 gap-12 gap-13 gap-14 gap-15 gap-16 gap-17 gap-18 gap-19 gap-20 gap-21 gap-22 gap-23 gap-24 gap-25 gap-26 gap-27 gap-28 gap-29 gap-30 gap-31 gap-32 gap-33 gap-34 gap-35 gap-36 gap-37 gap-38 gap-39 gap-40"></div>

{{-- @3xl responsive gap classes --}}
<div class="@3xl:gap-0 @3xl:gap-1 @3xl:gap-2 @3xl:gap-3 @3xl:gap-4 @3xl:gap-5 @3xl:gap-6 @3xl:gap-7 @3xl:gap-8 @3xl:gap-9 @3xl:gap-10 @3xl:gap-11 @3xl:gap-12 @3xl:gap-13 @3xl:gap-14 @3xl:gap-15 @3xl:gap-16 @3xl:gap-17 @3xl:gap-18 @3xl:gap-19 @3xl:gap-20 @3xl:gap-21 @3xl:gap-22 @3xl:gap-23 @3xl:gap-24 @3xl:gap-25 @3xl:gap-26 @3xl:gap-27 @3xl:gap-28 @3xl:gap-29 @3xl:gap-30 @3xl:gap-31 @3xl:gap-32 @3xl:gap-33 @3xl:gap-34 @3xl:gap-35 @3xl:gap-36 @3xl:gap-37 @3xl:gap-38 @3xl:gap-39 @3xl:gap-40"></div>

{{-- @7xl responsive gap classes --}}
<div class="@7xl:gap-0 @7xl:gap-1 @7xl:gap-2 @7xl:gap-3 @7xl:gap-4 @7xl:gap-5 @7xl:gap-6 @7xl:gap-7 @7xl:gap-8 @7xl:gap-9 @7xl:gap-10 @7xl:gap-11 @7xl:gap-12 @7xl:gap-13 @7xl:gap-14 @7xl:gap-15 @7xl:gap-16 @7xl:gap-17 @7xl:gap-18 @7xl:gap-19 @7xl:gap-20 @7xl:gap-21 @7xl:gap-22 @7xl:gap-23 @7xl:gap-24 @7xl:gap-25 @7xl:gap-26 @7xl:gap-27 @7xl:gap-28 @7xl:gap-29 @7xl:gap-30 @7xl:gap-31 @7xl:gap-32 @7xl:gap-33 @7xl:gap-34 @7xl:gap-35 @7xl:gap-36 @7xl:gap-37 @7xl:gap-38 @7xl:gap-39 @7xl:gap-40"></div>
