{{-- Auto-generated Tailwind safe classes for padding --}}
{{-- Generated by: php scripts/generate_safe_classes.php --}}

{{-- Padding all classes --}}
<div class="p-0 p-px p-0.5 p-1 p-1.5 p-2 p-2.5 p-3 p-3.5 p-4 p-5 p-6 p-7 p-8 p-9 p-10 p-11 p-12 p-14 p-16 p-20 p-24 p-28 p-32 p-36 p-40 p-44 p-48 p-52 p-56 p-60 p-64 p-72 p-80 p-96"></div>

{{-- @3xl responsive padding all classes --}}
<div class="@3xl:p-0 @3xl:p-px @3xl:p-0.5 @3xl:p-1 @3xl:p-1.5 @3xl:p-2 @3xl:p-2.5 @3xl:p-3 @3xl:p-3.5 @3xl:p-4 @3xl:p-5 @3xl:p-6 @3xl:p-7 @3xl:p-8 @3xl:p-9 @3xl:p-10 @3xl:p-11 @3xl:p-12 @3xl:p-14 @3xl:p-16 @3xl:p-20 @3xl:p-24 @3xl:p-28 @3xl:p-32 @3xl:p-36 @3xl:p-40 @3xl:p-44 @3xl:p-48 @3xl:p-52 @3xl:p-56 @3xl:p-60 @3xl:p-64 @3xl:p-72 @3xl:p-80 @3xl:p-96"></div>

{{-- @5xl responsive padding all classes --}}
<div class="@5xl:p-0 @5xl:p-px @5xl:p-0.5 @5xl:p-1 @5xl:p-1.5 @5xl:p-2 @5xl:p-2.5 @5xl:p-3 @5xl:p-3.5 @5xl:p-4 @5xl:p-5 @5xl:p-6 @5xl:p-7 @5xl:p-8 @5xl:p-9 @5xl:p-10 @5xl:p-11 @5xl:p-12 @5xl:p-14 @5xl:p-16 @5xl:p-20 @5xl:p-24 @5xl:p-28 @5xl:p-32 @5xl:p-36 @5xl:p-40 @5xl:p-44 @5xl:p-48 @5xl:p-52 @5xl:p-56 @5xl:p-60 @5xl:p-64 @5xl:p-72 @5xl:p-80 @5xl:p-96"></div>

{{-- Padding top classes --}}
<div class="pt-0 pt-px pt-0.5 pt-1 pt-1.5 pt-2 pt-2.5 pt-3 pt-3.5 pt-4 pt-5 pt-6 pt-7 pt-8 pt-9 pt-10 pt-11 pt-12 pt-14 pt-16 pt-20 pt-24 pt-28 pt-32 pt-36 pt-40 pt-44 pt-48 pt-52 pt-56 pt-60 pt-64 pt-72 pt-80 pt-96"></div>

{{-- @3xl responsive padding top classes --}}
<div class="@3xl:pt-0 @3xl:pt-px @3xl:pt-0.5 @3xl:pt-1 @3xl:pt-1.5 @3xl:pt-2 @3xl:pt-2.5 @3xl:pt-3 @3xl:pt-3.5 @3xl:pt-4 @3xl:pt-5 @3xl:pt-6 @3xl:pt-7 @3xl:pt-8 @3xl:pt-9 @3xl:pt-10 @3xl:pt-11 @3xl:pt-12 @3xl:pt-14 @3xl:pt-16 @3xl:pt-20 @3xl:pt-24 @3xl:pt-28 @3xl:pt-32 @3xl:pt-36 @3xl:pt-40 @3xl:pt-44 @3xl:pt-48 @3xl:pt-52 @3xl:pt-56 @3xl:pt-60 @3xl:pt-64 @3xl:pt-72 @3xl:pt-80 @3xl:pt-96"></div>

{{-- @5xl responsive padding top classes --}}
<div class="@5xl:pt-0 @5xl:pt-px @5xl:pt-0.5 @5xl:pt-1 @5xl:pt-1.5 @5xl:pt-2 @5xl:pt-2.5 @5xl:pt-3 @5xl:pt-3.5 @5xl:pt-4 @5xl:pt-5 @5xl:pt-6 @5xl:pt-7 @5xl:pt-8 @5xl:pt-9 @5xl:pt-10 @5xl:pt-11 @5xl:pt-12 @5xl:pt-14 @5xl:pt-16 @5xl:pt-20 @5xl:pt-24 @5xl:pt-28 @5xl:pt-32 @5xl:pt-36 @5xl:pt-40 @5xl:pt-44 @5xl:pt-48 @5xl:pt-52 @5xl:pt-56 @5xl:pt-60 @5xl:pt-64 @5xl:pt-72 @5xl:pt-80 @5xl:pt-96"></div>

{{-- Padding right classes --}}
<div class="pr-0 pr-px pr-0.5 pr-1 pr-1.5 pr-2 pr-2.5 pr-3 pr-3.5 pr-4 pr-5 pr-6 pr-7 pr-8 pr-9 pr-10 pr-11 pr-12 pr-14 pr-16 pr-20 pr-24 pr-28 pr-32 pr-36 pr-40 pr-44 pr-48 pr-52 pr-56 pr-60 pr-64 pr-72 pr-80 pr-96"></div>

{{-- @3xl responsive padding right classes --}}
<div class="@3xl:pr-0 @3xl:pr-px @3xl:pr-0.5 @3xl:pr-1 @3xl:pr-1.5 @3xl:pr-2 @3xl:pr-2.5 @3xl:pr-3 @3xl:pr-3.5 @3xl:pr-4 @3xl:pr-5 @3xl:pr-6 @3xl:pr-7 @3xl:pr-8 @3xl:pr-9 @3xl:pr-10 @3xl:pr-11 @3xl:pr-12 @3xl:pr-14 @3xl:pr-16 @3xl:pr-20 @3xl:pr-24 @3xl:pr-28 @3xl:pr-32 @3xl:pr-36 @3xl:pr-40 @3xl:pr-44 @3xl:pr-48 @3xl:pr-52 @3xl:pr-56 @3xl:pr-60 @3xl:pr-64 @3xl:pr-72 @3xl:pr-80 @3xl:pr-96"></div>

{{-- @5xl responsive padding right classes --}}
<div class="@5xl:pr-0 @5xl:pr-px @5xl:pr-0.5 @5xl:pr-1 @5xl:pr-1.5 @5xl:pr-2 @5xl:pr-2.5 @5xl:pr-3 @5xl:pr-3.5 @5xl:pr-4 @5xl:pr-5 @5xl:pr-6 @5xl:pr-7 @5xl:pr-8 @5xl:pr-9 @5xl:pr-10 @5xl:pr-11 @5xl:pr-12 @5xl:pr-14 @5xl:pr-16 @5xl:pr-20 @5xl:pr-24 @5xl:pr-28 @5xl:pr-32 @5xl:pr-36 @5xl:pr-40 @5xl:pr-44 @5xl:pr-48 @5xl:pr-52 @5xl:pr-56 @5xl:pr-60 @5xl:pr-64 @5xl:pr-72 @5xl:pr-80 @5xl:pr-96"></div>

{{-- Padding bottom classes --}}
<div class="pb-0 pb-px pb-0.5 pb-1 pb-1.5 pb-2 pb-2.5 pb-3 pb-3.5 pb-4 pb-5 pb-6 pb-7 pb-8 pb-9 pb-10 pb-11 pb-12 pb-14 pb-16 pb-20 pb-24 pb-28 pb-32 pb-36 pb-40 pb-44 pb-48 pb-52 pb-56 pb-60 pb-64 pb-72 pb-80 pb-96"></div>

{{-- @3xl responsive padding bottom classes --}}
<div class="@3xl:pb-0 @3xl:pb-px @3xl:pb-0.5 @3xl:pb-1 @3xl:pb-1.5 @3xl:pb-2 @3xl:pb-2.5 @3xl:pb-3 @3xl:pb-3.5 @3xl:pb-4 @3xl:pb-5 @3xl:pb-6 @3xl:pb-7 @3xl:pb-8 @3xl:pb-9 @3xl:pb-10 @3xl:pb-11 @3xl:pb-12 @3xl:pb-14 @3xl:pb-16 @3xl:pb-20 @3xl:pb-24 @3xl:pb-28 @3xl:pb-32 @3xl:pb-36 @3xl:pb-40 @3xl:pb-44 @3xl:pb-48 @3xl:pb-52 @3xl:pb-56 @3xl:pb-60 @3xl:pb-64 @3xl:pb-72 @3xl:pb-80 @3xl:pb-96"></div>

{{-- @5xl responsive padding bottom classes --}}
<div class="@5xl:pb-0 @5xl:pb-px @5xl:pb-0.5 @5xl:pb-1 @5xl:pb-1.5 @5xl:pb-2 @5xl:pb-2.5 @5xl:pb-3 @5xl:pb-3.5 @5xl:pb-4 @5xl:pb-5 @5xl:pb-6 @5xl:pb-7 @5xl:pb-8 @5xl:pb-9 @5xl:pb-10 @5xl:pb-11 @5xl:pb-12 @5xl:pb-14 @5xl:pb-16 @5xl:pb-20 @5xl:pb-24 @5xl:pb-28 @5xl:pb-32 @5xl:pb-36 @5xl:pb-40 @5xl:pb-44 @5xl:pb-48 @5xl:pb-52 @5xl:pb-56 @5xl:pb-60 @5xl:pb-64 @5xl:pb-72 @5xl:pb-80 @5xl:pb-96"></div>

{{-- Padding left classes --}}
<div class="pl-0 pl-px pl-0.5 pl-1 pl-1.5 pl-2 pl-2.5 pl-3 pl-3.5 pl-4 pl-5 pl-6 pl-7 pl-8 pl-9 pl-10 pl-11 pl-12 pl-14 pl-16 pl-20 pl-24 pl-28 pl-32 pl-36 pl-40 pl-44 pl-48 pl-52 pl-56 pl-60 pl-64 pl-72 pl-80 pl-96"></div>

{{-- @3xl responsive padding left classes --}}
<div class="@3xl:pl-0 @3xl:pl-px @3xl:pl-0.5 @3xl:pl-1 @3xl:pl-1.5 @3xl:pl-2 @3xl:pl-2.5 @3xl:pl-3 @3xl:pl-3.5 @3xl:pl-4 @3xl:pl-5 @3xl:pl-6 @3xl:pl-7 @3xl:pl-8 @3xl:pl-9 @3xl:pl-10 @3xl:pl-11 @3xl:pl-12 @3xl:pl-14 @3xl:pl-16 @3xl:pl-20 @3xl:pl-24 @3xl:pl-28 @3xl:pl-32 @3xl:pl-36 @3xl:pl-40 @3xl:pl-44 @3xl:pl-48 @3xl:pl-52 @3xl:pl-56 @3xl:pl-60 @3xl:pl-64 @3xl:pl-72 @3xl:pl-80 @3xl:pl-96"></div>

{{-- @5xl responsive padding left classes --}}
<div class="@5xl:pl-0 @5xl:pl-px @5xl:pl-0.5 @5xl:pl-1 @5xl:pl-1.5 @5xl:pl-2 @5xl:pl-2.5 @5xl:pl-3 @5xl:pl-3.5 @5xl:pl-4 @5xl:pl-5 @5xl:pl-6 @5xl:pl-7 @5xl:pl-8 @5xl:pl-9 @5xl:pl-10 @5xl:pl-11 @5xl:pl-12 @5xl:pl-14 @5xl:pl-16 @5xl:pl-20 @5xl:pl-24 @5xl:pl-28 @5xl:pl-32 @5xl:pl-36 @5xl:pl-40 @5xl:pl-44 @5xl:pl-48 @5xl:pl-52 @5xl:pl-56 @5xl:pl-60 @5xl:pl-64 @5xl:pl-72 @5xl:pl-80 @5xl:pl-96"></div>

{{-- Padding horizontal classes --}}
<div class="px-0 px-px px-0.5 px-1 px-1.5 px-2 px-2.5 px-3 px-3.5 px-4 px-5 px-6 px-7 px-8 px-9 px-10 px-11 px-12 px-14 px-16 px-20 px-24 px-28 px-32 px-36 px-40 px-44 px-48 px-52 px-56 px-60 px-64 px-72 px-80 px-96"></div>

{{-- @3xl responsive padding horizontal classes --}}
<div class="@3xl:px-0 @3xl:px-px @3xl:px-0.5 @3xl:px-1 @3xl:px-1.5 @3xl:px-2 @3xl:px-2.5 @3xl:px-3 @3xl:px-3.5 @3xl:px-4 @3xl:px-5 @3xl:px-6 @3xl:px-7 @3xl:px-8 @3xl:px-9 @3xl:px-10 @3xl:px-11 @3xl:px-12 @3xl:px-14 @3xl:px-16 @3xl:px-20 @3xl:px-24 @3xl:px-28 @3xl:px-32 @3xl:px-36 @3xl:px-40 @3xl:px-44 @3xl:px-48 @3xl:px-52 @3xl:px-56 @3xl:px-60 @3xl:px-64 @3xl:px-72 @3xl:px-80 @3xl:px-96"></div>

{{-- @5xl responsive padding horizontal classes --}}
<div class="@5xl:px-0 @5xl:px-px @5xl:px-0.5 @5xl:px-1 @5xl:px-1.5 @5xl:px-2 @5xl:px-2.5 @5xl:px-3 @5xl:px-3.5 @5xl:px-4 @5xl:px-5 @5xl:px-6 @5xl:px-7 @5xl:px-8 @5xl:px-9 @5xl:px-10 @5xl:px-11 @5xl:px-12 @5xl:px-14 @5xl:px-16 @5xl:px-20 @5xl:px-24 @5xl:px-28 @5xl:px-32 @5xl:px-36 @5xl:px-40 @5xl:px-44 @5xl:px-48 @5xl:px-52 @5xl:px-56 @5xl:px-60 @5xl:px-64 @5xl:px-72 @5xl:px-80 @5xl:px-96"></div>

{{-- Padding vertical classes --}}
<div class="py-0 py-px py-0.5 py-1 py-1.5 py-2 py-2.5 py-3 py-3.5 py-4 py-5 py-6 py-7 py-8 py-9 py-10 py-11 py-12 py-14 py-16 py-20 py-24 py-28 py-32 py-36 py-40 py-44 py-48 py-52 py-56 py-60 py-64 py-72 py-80 py-96"></div>

{{-- @3xl responsive padding vertical classes --}}
<div class="@3xl:py-0 @3xl:py-px @3xl:py-0.5 @3xl:py-1 @3xl:py-1.5 @3xl:py-2 @3xl:py-2.5 @3xl:py-3 @3xl:py-3.5 @3xl:py-4 @3xl:py-5 @3xl:py-6 @3xl:py-7 @3xl:py-8 @3xl:py-9 @3xl:py-10 @3xl:py-11 @3xl:py-12 @3xl:py-14 @3xl:py-16 @3xl:py-20 @3xl:py-24 @3xl:py-28 @3xl:py-32 @3xl:py-36 @3xl:py-40 @3xl:py-44 @3xl:py-48 @3xl:py-52 @3xl:py-56 @3xl:py-60 @3xl:py-64 @3xl:py-72 @3xl:py-80 @3xl:py-96"></div>

{{-- @5xl responsive padding vertical classes --}}
<div class="@5xl:py-0 @5xl:py-px @5xl:py-0.5 @5xl:py-1 @5xl:py-1.5 @5xl:py-2 @5xl:py-2.5 @5xl:py-3 @5xl:py-3.5 @5xl:py-4 @5xl:py-5 @5xl:py-6 @5xl:py-7 @5xl:py-8 @5xl:py-9 @5xl:py-10 @5xl:py-11 @5xl:py-12 @5xl:py-14 @5xl:py-16 @5xl:py-20 @5xl:py-24 @5xl:py-28 @5xl:py-32 @5xl:py-36 @5xl:py-40 @5xl:py-44 @5xl:py-48 @5xl:py-52 @5xl:py-56 @5xl:py-60 @5xl:py-64 @5xl:py-72 @5xl:py-80 @5xl:py-96"></div>
